#! /bin/sh

../../stu 2>list.err '@ do'
exitcode="$?"

if [ "$exitcode" != 1 ]; then
    echo >&2 "$0:  *** invalid exit code '$exitcode'"
    exit 1
fi

fgrep -q "No rule to build @' do'" list.err || {
    echo >&2 "$0:  *** invalid error output"
	echo >&2 ___________________
	cat >&2 list.err
	echo >&2 ___________________
    exit 1
}

exit 0
