#!/bin/sh
#
# Trivial dependencies.
#
# * (1) stu
#	* B, D, C and A are built
# * (2) touch D
# * stu
#	* nothing is done
# * (3) rm D
# * stu
#	* nothing is done
# * (4) touch B
# * stu
#	* D, C and A are rebuilt
# * (5) touch B
# * stu
#	* A is rebuilt
#

. ../../sh/test.sh

rm -f ?

#
# (1)
#

set +e
../../bin/stu.test >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 0 ] || Error 'exit status (1)'
[ -r A ] && [ -r B ] && [ -r C ] && [ -r D ] || Error 'files (1)'

#
# (2)
#

../../sh/touch_old A 2
../../sh/touch_old B 2
../../sh/touch_old C 2
touch D

set +e
../../bin/stu.test >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 0 ] || Error 'exit status (2)'
diff list.out stdout-2 || Error 'stdout (2)'
[ -r list.err ] && [ ! -s list.err ] || Error 'stderr (2)'

#
# (3)
#

rm D

set +e
../../bin/stu.test >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 0 ] || Error 'exit status (3)'
diff list.out stdout-3 || Error 'stdout (3)'
[ -r list.err ] && [ ! -s list.err ] || Error 'stderr (3)'

#
# (4)
#

../../sh/touch_old A 2
../../sh/touch_old C 2
touch B

set +e
../../bin/stu.test >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 0 ] || Error 'exit status (4)'
diff list.out stdout-4 || Error 'stdout (4)'
[ -r list.err ] && [ ! -s list.err ] || Error 'stderr (4)'

#
# (5)
#

../../sh/touch_old A 2
../../sh/touch_old C 2
../../sh/touch_old D 2
touch B

set +e
../../bin/stu.test >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 0 ] || Error 'exit status (5)'
diff list.out stdout-5 || Error 'stdout (5)'
[ -r list.err ] && [ ! -s list.err ] || Error 'stderr (5)'
