#! /bin/sh

#
# (1) 'A' is up to date
#

touch A

../../stu.test -q >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** (1) Exit code"
	exit 1
}

grep -qF 'Nothing to be done' list.out || {
	echo >&2 "*** (1) stdout"
	exit 1
}

[ -r list.err -a \! -s list.err ] || {
	echo >&2 "*** (1) stderr"
	exit 1
}

#
# (2) 'A' does not exist
#

rm -f A 

../../stu.test -q >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "*** (2) Exit code"
	exit 1
}

grep -qF 'Targets are not up to date' list.out || {
	echo >&2 "*** (2) stdout"
	exit 1
}

[ -r list.err -a \! -s list.err ] || {
	echo >&2 "*** (2) stderr"
	exit 1
}

exit 0
