#!/bin/sh
#
# Trivial dependencies.
#
# * (0) stu
#	* B, D, C and A are built
# * (1) touch C
# * stu
#	* nothing is done
# * (2) touch D
# * stu
#	* nothing is done
# * (3) rm D
# * stu
#	* nothing is done
# * (4) touch B
# * stu
#	* D, C and A are rebuilt
# * (5) touch B
# * stu
#	* A is rebuilt
#

. ../../sh/test.sh

rm -f ?

#
# (0)
#

../../bin/stu.test >list.out 2>list.err

diff list.out stdout-0 || Error '(0out)'
[ -r list.err ] && [ ! -s list.err ] || Error '(0err)'

#
# (1)
#

../../sh/touch_old D
../../sh/touch_old B
../../sh/touch_old A
touch C

../../bin/stu.test >list.out 2>list.err

diff list.out stdout-1 || Error '(1out)'
[ -r list.err ] && [ ! -s list.err ] || Error '(1err)'

#
# (2)
#

../../sh/touch_old C
../../sh/touch_old B
../../sh/touch_old A
touch D

../../bin/stu.test >list.out 2>list.err

diff list.out stdout-2 || Error '(2out)'
[ -r list.err ] && [ ! -s list.err ] || Error '(2err)'

#
# (3)
#

rm D

../../bin/stu.test >list.out 2>list.err

diff list.out stdout-3 || Error '(3out)'
[ -r list.err ] && [ ! -s list.err ] || Error '(3err)'

#
# (4)
#

../../sh/touch_old C
../../sh/touch_old A
touch B

../../bin/stu.test >list.out 2>list.err

diff list.out stdout-4 || Error '(4out)'
[ -r list.err ] && [ ! -s list.err ] || Error '(4err)'

#
# (5)
#

../../sh/touch_old D
../../sh/touch_old C
../../sh/touch_old A
touch B

../../bin/stu.test >list.out 2>list.err

diff list.out stdout-5 || Error '(5out)'
[ -r list.err ] && [ ! -s list.err ] || Error '(5err)'
