#!/bin/sh
. ../../sh/test.sh

echo >&3 '../../bin/stu.test -j1000 &'
../../bin/stu.test -j1000 >list.out 2>list.err & pid=$!

# Wait until a first line has been written
begin=$(../../sh/now)
while [ \! -s list.out ] ; do
	now=$(../../sh/now)
	if [ "$now" -gt "$((begin + 2))" ] ; then
		echo >&2 '*** No output written in first 2 seconds'
		break
	fi
done

echo >&3 "kill -s USR1 $pid"
kill -s USR1 "$pid"

echo >&3 sleep 1
sleep 1
echo >&3 done sleeping

count=$(echo $(ps -fA | grep 7463194 | grep -v grep | wc -l))
echo >&3 "count=$count"
[ "$count" != 0 ] || Error 'Stu must still be running'

grep -q -E -e '^STATISTICS  ' list.out

kill -INT "$pid"
sleep 1

if [ "$(echo $(ps -fA | grep -F -e '7463194' | grep -v grep | wc -l))" \!= 0 ]; then
	Error 'Stu is still running'
fi

exit 0
