#! /bin/sh

../../stu.test -P >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 '*** Exit code'
	exit 1
}

[ -r list.err ] && [ ! -s list.err ] || {
	echo >&2 '*** Stderr'
	exit 1
}


[ -r list.out ] && [ ! -s list.out ] || {
	echo >&2 '*** Stdout'
	exit 1
}

exit 0
