#! /bin/sh

set -e

rm -f ? list.*

#
# Run stu
#

../../stu.test -d >list.out 2>list.err

[ -r B ] || {
	echo >&2 "*** 'B' must be created"
	exit 1
}

#
# Change 'B' 
#

../../sh/touch_old A 2
touch B

#
# Run 'B' -- 'B' is rebuilt 
#

../../stu.test -d >list.out 2>list.err

set +e
grep -qF 'Nothing to be done' list.out 
[ "$?" = 1 ] || {
	echo >&2 "*** 'Nothing to be done' must not be found in output"
	exit 1
}

rm -f ? list.* || exit 1

exit 0
