#! /bin/sh

rm -f ? list.* || exit 2

echo ../../bin/stu.test -j50
../../bin/stu.test -j50 >list.out 2>list.err &
pid=$!

echo sleep 3
sleep 3 || exit 2
kill "$pid" || exit 2
wait "$!" 2>/dev/null
exitstatus=$?

[ "$exitstatus" != 0 ] || {
	echo >&2 "*** Expected an error"
	exit 1
}

grep -qF 'removing partially built files (30)' list.err || {
	echo >&2 "*** Expecting number of removed files"
	echo >&2 '___ list.err ___'
	cat  >&2 list.err
	echo >&2 '________________'
	exit 1
}

exit 0
