#! /bin/sh
# 
# What happens when standard input is read twice from the command line.  
#
# stdin will be read just once, because we filter multiple input files. 
#

rm -f A

cat <<EOF | ../../stu -f - -f - 
A = { correct }
EOF
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** Exit code"
	exit 1
}

[ -r A ] || {
	echo >&2 "*** Existence"
	exit 1
}

grep -qF correct A || {
	echo >&2 "*** Content"
	exit 1
}

exit 0
