#! /bin/sh
#
# Rudimentary fuzz testing.  Run Stu on an input file with random bytes.  If
# something goes wrong (i.e., an assertion fails), the exit status is
# 128+SIGABRT. 
#

set -e

../../sh/seq 1000 |
while read line ; do
	rm -f list.*
	dd if=/dev/urandom bs=1 count=3  >list.stu 2>/dev/null
	set +e
	../../bin/stu.test -f list.stu >list.out 2>list.err
	exitstatus=$?
	set -e
	if [ "$exitstatus" -gt 4 ] ; then
		echo >&2 '*** Error'
		echo "exitstatus=$exitstatus"
		hexdump -C list.stu
		exit 1
	fi
done

exit 0
