#! /bin/sh
#
# We must have an own EXEC file here because the default text mechanism
# executes the test a second time, and checks that "Noting to be done"
# is output.  This is not the case however, since because the file 'B'
# has a modification time in the future, 'A' always has to be rebuilt
# (except if we wait until B's timestamp has passed.)
#

rm -f ? || exit 1

../../stu.test >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** Exit code must be zero (1)"
	exit 1
}

diff list.err stderr-correct || {
	echo >&2 "*** Missing warning about future timestamp of 'B' (1)"
	echo >&2 list.err:
	echo >&2 __________
	cat >&2 list.err
	echo >&2 __________
	echo >&2 stderr-correct:
	echo >&2 __________
	cat >&2 stderr-correct
	echo >&2 __________
	exit 1
}

# Execute again:  The warning must still be output.

../../stu.test >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** Exit code must be zero (2)"
	exit 1
}

diff list.err stderr-correct.2 || {
	echo >&2 "*** Missing warning about future timestamp of 'B' (2)"
	echo >&2 list.err:
	echo >&2 __________
	cat >&2 list.err
	echo >&2 __________
	exit 1
}

rm -f ? || exit 1

exit 0
