#! /bin/sh

../../stu.test -P -f a.stu -f b.stu >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** Exit code"
	exit 1
}

[ -r list.err ] && [ ! -s list.err ] || {
	echo >&2 "*** stderr"
	exit 1
}

grep -qF 'list.XYZPQR' list.out || {
	echo >&2 "*** stdout"
	exit 1
}

exit 0
