#! /bin/sh

rm -f ? || exit 1

touch C || exit 1

../../stu.test >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 '*** exit code'
	exit 1
}

diff list.out stdout-correct || {
	echo >&2 '*** stdout'
	exit 1
}

exit 0
