#! /bin/sh

rm -f ? || exit 2
touch C || exit 2

../../bin/stu.test >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo >&2 '*** Exit status incorrect'
	exit 1
}

diff list.out stdout-correct || {
	echo >&2 '*** stdout'
	exit 1
}

exit 0
