#! /bin/sh
#
# This test is also used by "make prof".
#

rm -f ? list.* || exit 2

../../bin/stu.test -j 010 >list.out 2>list.err &
pid=$!

sleep 3 || exit 2

[ -e A ] || {
	kill -9 "$pid"
	echo >&2 "*** Expected Stu to be done"
	exit 1
}

wait "$pid" 2>/dev/null

exit 0
