#!/bin/sh
. ../../sh/test.sh

echo CORRECT >BBB.data

../../bin/stu.test

grep -q -F -e 'CORRECT' BBB.data

../../bin/stu.test >list.out
grep -q -F -x -e 'Targets are up to date' list.out

../../sh/touch_old A 1
touch BBB.data

../../bin/stu.test >list.out

grep -q -F -e 'cat BBB.data' list.out

../../bin/stu.test >list.out

grep -q -F -x -e 'Targets are up to date' list.out
