#!/bin/sh
. ../../sh/test.sh

rm -Rf BBB A

echo CORRECT >BBB

../../bin/stu.test || Error '(A) exit status'

grep -q -F -e 'CORRECT' BBB || Error '(A) BBB'

../../bin/stu.test >list.content || Error '(B) exit status'

grep -q -F -x -e 'Targets are up to date' list.content || Error '(B) stdout'

../../sh/touch_old A 1
touch BBB

../../bin/stu.test >list.content || Error '(C) exit status'

grep -q -F -e 'cat BBB' list.content || Error '(C) stdout'

../../bin/stu.test >list.content || Error '(D) exit status'

grep -q -F -x -e 'Targets are up to date' list.content || Error '(D) stdout'

rm -f BBB
