#! /bin/sh

rm -f ?

../../stu.test >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 '*** Invalid exit code'
	exit 1
}

[ -e A ] && {
	echo >&2 "*** 'A' was not removed"
	exit 1
}

exit 0
