#! /bin/sh

rm -f ? || exit 2

../../bin/stu.test >list.out 2>list.err
exitstatus="$?"

[ "$exitstatus" = 1 ] || {
	echo >&2 '*** Invalid exit status'
	exit 1
}

[ -e A ] && {
	echo >&2 "*** 'A' was not removed"
	exit 1
}

exit 0
