#! /bin/sh

rm -f list.err || exit 1

echo ../../stu.test
../../stu.test 2>list.err
exitcode="$?"

if [ "$exitcode" != 1 ] ; then
	echo '*** (A)'
	exit 1
fi

# Some shell with output $0, and some won't.  We can't do more here
# than check for the filename.

grep -Eq 'wefvunwoiefuvuviwwve' list.err || {
	echo '*** (B)'
	echo 'list.err:'
	echo ____________
	cat list.err
	echo ____________
	exit 1
}

exit 0
