#! /bin/sh

rm -f ? || exit 2

../../bin/stu.test -ds >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo >&2 '*** Exit status' ; exit 1 ;
}

[ -r list.out ] && [ ! -s list.out ] || { echo >&2 '*** Stdout not empty' ; exit 1 ; }
[ -r list.err ] && [ -s list.err ] || { echo >&2 '*** Stderr empty' ; exit 1 ; }

lines=$(echo $(<list.err wc -l))
[ "$lines" -gt 10 ] || { echo >&2 '*** Not enough error output' ; exit 1 ; }
grep -Eqv '^DEBUG  ' list.err && { echo >&2 '*** Invalid error output' ; exit 1 ; }

exit 0
