#! /bin/sh

../../stu -f '' 2>list.err
exitcode="$?"

if [ "$exitcode" != 4 ]; then
	echo >&2 "*** Wrong exit code"
	exit 1
fi

if ! grep -Fq "./stu: *** Option -f must take non-empty argument" list.err ; then
	echo >&2 "*** Missing error message"
	exit 1
fi

exit 0
