#! /bin/sh

../../stu.test -f '' 2>list.err
exitcode="$?"

[ "$exitcode" = 4 ] || {
	echo >&2 "*** Exit code"
	exit 1
}

grep -qF "Option -f: expected non-empty argument" list.err || {
	echo >&2 "*** Error output"
	exit 1
}

exit 0
