#!/bin/sh
. ../../sh/test.sh

rm -f A

# By calling stu

../../bin/stu.test
[ -r A ]

../../bin/stu.test >list.out
grep -q -F -e 'Targets are up to date' list.out

../../bin/stu.test @clean
[ ! -r A ]

# By calling stu A

../../bin/stu.test A
[ -r A ]

../../bin/stu.test A >list.out
grep -q -F -e 'Targets are up to date' list.out

../../bin/stu.test @clean
[ ! -r A ]
