#! /bin/sh

rm -Rf BBB A || exit 1

echo CORRECT >BBB

echo ../../stu.test
../../stu.test || {
	echo >&2 "$0:  *** stu failed (run A)"
	exit 1
}

grep -qF CORRECT BBB || {
	echo >&2 "$0:  *** 'CORRECT' not found in 'BBB'"
	exit 1
}

echo ../../stu.test
../../stu.test >list.content || {
	echo "$0:  *** stu failed (run B)"
	exit 1
}

grep -qFx 'Targets are up to date' list.content || {
	echo >&2 "$0:  *** 'Targets are up to date' not found in output'"
	exit 1
}

../../sh/touch_old A 1 || exit 1
touch BBB || exit 1

echo ../../stu.test
../../stu.test >list.content || {
	echo >&2 "$0:  *** stu failed (run C)"
	exit 1
}

grep -qF 'cat BBB' list.content || {
	echo >&2 "$0:  *** 'cat BBB' not found in output"
	exit 1
}

echo ../../stu.test
../../stu.test >list.content || {
	echo >&2 "$0:  *** stu failed (run D)"
	exit 1
}

grep -qFx 'Targets are up to date' list.content || {
	echo >&2 "$0:  *** 'Targets are up to date' not found in output'"
	exit 1
}

rm -f BBB || exit 1

exit 0
