#! /bin/sh

doo() { echo "$@" ; "$@" ; }

doo rm -Rf BBB A

echo CORRECT >BBB

echo ../../stu.test
../../stu.test || {
	echo >&2 "$0:  *** stu failed (run A)"
	exit 1
}

grep -qF CORRECT BBB || {
	echo >&2 "$0:  *** 'CORRECT' not found in 'BBB'"
	exit 1
}

echo ../../stu.test
../../stu.test >list.content || {
	echo "$0:  *** stu failed (run B)"
	exit 1
}

grep -qF 'Nothing to be done' list.content || {
	echo >&2 "$0:  *** 'Nothing to be done' not found in output'"
	exit 1
}

../../sh/touch_old A 1 || exit 1
touch BBB || exit 1

echo ../../stu.test
../../stu.test >list.content || {
	echo >&2 "$0:  *** stu failed (run C)"
	exit 1
}

grep -qF 'cat BBB' list.content || {
	echo >&2 "$0:  *** 'cat BBB' not found in output"
	exit 1
}

echo ../../stu.test
../../stu.test >list.content || {
	echo >&2 "$0:  *** stu failed (run D)"
	exit 1
}

grep -qF 'Nothing to be done' list.content || {
	echo >&2 "$0:  *** 'Nothing to be done' not found in output'"
	exit 1
}

rm -f BBB

exit 0
