#! /bin/sh

rm -f ? || exit 2

../../sh/touch_old list.x 1 || exit 2
touch x.data || exit 2

../../bin/stu.test -c list.x >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo >&2 "*** Exit code"
	exit 1
}

grep -qxF 'Targets are up to date' list.out || {
	echo >&2 "*** Output"
	exit 1
}

[ -r list.err ] && ! [ -s list.err ] || {
	echo >&2 "*** Error output"
	exit 1
}

exit 0
