#! /bin/sh
#
# Test that '-f -' makes Stu read standard input as an input file. 
#

../../bin/stu.test -f - >list.out 2>list.err <<EOF 
A: B { cp B A }
>B { echo correct }
EOF
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo >&2 "*** Expected exit status 0, not '$exitstatus'" 
	exit 1
}

[ -r list.err ] && [ ! -s list.err ] || {
	echo >&2 '*** stderr'
	exit 1
}

grep -qE '^correct$' A || {
	echo >&2 '*** Content'
	exit 1
}

exit 0
