#! /bin/sh

rm -f ? || exit 2

echo CORRECT1 >B || exit 2

../../bin/stu.test >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo >&2 '*** error'
	exit 1
}

echo A:
echo _____
cat A
echo _____

diff A content-correct || {
	echo >&2 '*** different content'
	exit 1
}

exit 0
