#! /bin/sh

rm -f ? || exit 1

echo CORRECT1 >B

../../stu.test >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 '*** error'
	exit 1
}

echo A:
echo _____
cat A
echo _____

diff A content-correct || {
	echo >&2 '*** different content'
	exit 1
}

exit 0
