#!/bin/sh
. ../../sh/test.sh

rm -f ? list.*
../../sh/touch_old A 2

set +e
../../bin/stu.test >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 0 ] || Error 'exit status'
[ -e B ] || Error 'B'
grep -q -F -x -e 'correct' A || Error 'A'
