#! /bin/sh

echo ../../bin/stu.test
../../bin/stu.test >list.out 2>list.err
exitstatus=$?

if [ "$exitstatus" != 0 ]; then
	echo >&2 "$0:  *** stu error"
	exit 1
fi

if ! grep -F CORRECT list.out ; then
	echo >&2 "$0:  *** output does not contain 'CORRECT'"
	exit 1
fi

exit 0
