#! /bin/sh

rm -f ? || exit 2

ln -s W B || exit 2

echo ../../bin/stu.test 
../../bin/stu.test >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo >&2 "*** invalid exit status"
	exit 1
}

echo STDOUT:
cat  list.out
echo _______
echo STDERR:
cat  list.err
echo _______

grep -qF 'Executing B' list.out || {
	echo >&2 "*** Invalid output"
	exit 1
}

rm -f ? || exit 2

exit 0
