#! /bin/sh

#
# (1) 'A' is up to date
#

touch A || exit 2

../../bin/stu.test -q >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo >&2 "*** (1) Exit status"
	exit 1
}

grep -qF 'Targets are up to date' list.out || {
	echo >&2 "*** (1) stdout"
	exit 1
}

[ -r list.err ] && [ ! -s list.err ] || {
	echo >&2 "*** (1) stderr"
	exit 1
}

#
# (2) 'A' does not exist
#

rm -f A || exit 2

../../bin/stu.test -q >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 1 ] || {
	echo >&2 "*** (2) Exit status"
	exit 1
}

grep -qF 'Targets are not up to date' list.err || {
	echo >&2 "*** (2) stderr:  expected 'Targets are not up to date'"
	echo >&2 list.out
	echo >&2 _________
	cat  >&2 list.out
	echo >&2 _________
	exit 1
}

[ -r list.out ] && [ ! -s list.out ] || {
	echo >&2 "*** (2) stdout"
	exit 1
}

exit 0
