#
# Makefile that also enables the test.  
# 

all-test: \
    stu.debug stu \
    stu.text test_options test_sed \
    test_test.debug test_test.ndebug \
    test_comments

dist:  stu.1 version.hh stu.text

include Makefile

.PHONY:  all-test clean-test

clean-test:  clean
	rm -f stu.1 version.hh stu.prof stu stu.debug stu.text test_* error.log

# Some of the specialized flags may not be present in other
# compilers and compiler versions than those used by the authors.  Just
# remove the flags if you use such a compiler. 

CXXFLAGS_DEBUG=  -ggdb -Og \
    -Wall -Wextra -Wunused -pedantic \
    -Wundef -Wc++11-compat -Wwrite-strings -Wzero-as-null-pointer-constant -Wshadow \
    -Werror                 \
    -fno-gnu-keywords       \

CXXFLAGS_PROF=   -pg -O3 -DNDEBUG 

CXXFLAGS_ALL_DEBUG=  $(CXXFLAGS_DEBUG)  $(CXXFLAGS_OTHER)
CXXFLAGS_ALL_PROF=   $(CXXFLAGS_PROF)   $(CXXFLAGS_OTHER)

stu.debug:  *.cc *.hh version.hh
	$(CXX) $(CXXFLAGS_ALL_DEBUG)  stu.cc -o stu.debug

stu.prof: *.cc *.hh version.hh
	$(CXX) $(CXXFLAGS_ALL_PROF)   stu.cc -o stu.prof

test_options:  sh/testoptions stu.cc stu.1.in
	sh/testoptions && touch $@

test_sed: sh/testsed . test test/* test/*/* 
	sh/testsed && touch $@

test_test.debug: stu.debug sh/mktest test test/* test/*/* 
	sh/mktest && touch $@

test_test.ndebug: stu sh/mktest test test/* test/*/* 
	NDEBUG=1 sh/mktest && touch $@

test_comments:  *.cc *.hh sh/testcomments . test test/* test/*/* 
	sh/testcomments

stu.text:  stu.1
	MANWIDTH=80 man ./stu.1 >stu.text

# Note:  the ending ".1" indicates that the manpage is in Section 1
# (commands).  It has nothing to do with the version number of Stu. 
stu.1:  stu.1.in VERSION sh/mkman
	sh/mkman

version.hh:  VERSION sh/mkversion
	sh/mkversion >version.hh

analysis.prof:  gmon.out 	
	gprof stu.prof gmon.out >analysis.prof
