#! /bin/sh
#
# Test consistency of the options.
#

ret=0

#
# Check that both lists of options are the same
#

<stu.cc sed -re '/" *-[a-zA-Z]/!d;s,^.*" *-(.).*$,\1,' >testoptions.a
<stu.1.in sed -re '/\.IP\s(|")+-./!d;s,^\s*\.IP\s+(|")-(.).*$,\2,' >testoptions.b

if ! cmp testoptions.a testoptions.b ; then
	echo >&2 "$0: *** The options given and 'stu.cc' are different from those given in 'stu.1.in'"
	echo >&2 "Options from 'stu.cc':"
	cat >&2 testoptions.a
	echo >&2 "Options from 'stu.1.in':"
	cat >&2 testoptions.b
	ret=1
fi

rm -f testoptions.a testoptions.b

exit $ret
