/* Automatically generated by sh/mkversion on Fri Jun 10 12:58:02 CEST 2016 */

#ifndef VERSION_HH
#define VERSION_HH

#define STU_VERSION "1.15.37"

#define STU_VERSION_MAJOR 1
#define STU_VERSION_MINOR 15
#define STU_VERSION_PATCH 37

#endif /* ! VERSION_HH */
