/* Automatically generated by sh/mkversion on 2022-07-22T15:44:14 */

#ifndef VERSION_HH
#define VERSION_HH

#define STU_VERSION "2.7.8"

#define STU_VERSION_MAJOR 2
#define STU_VERSION_MINOR 7
#define STU_VERSION_PATCH 8

#endif /* ! VERSION_HH */
