/* Automatically generated by sh/mkversion on Tue Aug  2 22:16:37 CEST 2016 */

#ifndef VERSION_HH
#define VERSION_HH

#define STU_VERSION "1.15.85"

#define STU_VERSION_MAJOR 1
#define STU_VERSION_MINOR 15
#define STU_VERSION_PATCH 85

#endif /* ! VERSION_HH */
