#! /bin/sh

doo() { echo "$@" ; "$@" ; }

doo rm -rf ?

echo 'echo Hello >B'
echo Hello >B || {
    echo >&2 "$0:  *** Initialization failed"
    exit 1
}

echo >&2 ../../stu 
../../stu || {
    echo >&2 "$0:  *** Initial build failed"
    exit 1
}

# Note:  not sleeping may make the new file B have the exact same
# timestamp as the old A.  
sleep 1
doo echo "Hello CORRECT World" >B

ls -l A B

echo >&2 ../../stu 
../../stu || {
    echo >&2 "$0:  *** Second build failed"
    exit 1
}

if ! fgrep -l CORRECT A ; then
    echo >&2 "$0:  *** 'A' was not updated"
    exit 1
fi

doo rm -rf ?

exit 0
