#! /bin/sh

rm -f ? || exit 1

#
# Step 1:  build A:  everything is built
#

../../stu.test 
exitcode="$?"

if [ "$exitcode" != 0 ] ; then
	echo >&2 "*** wrong exit code"
	exit 1
fi

if [ ! -r A -o ! -r B -o ! -r C ] ; then
	echo >&2 "*** A/B/C were not built"
	exit 1
fi

#
# Step 2:  rm B; stu B:  B is re-built
#

../../sh/touch_old A 1 || exit 1
../../sh/touch_old C 1 || exit 1

rm -f B

../../stu.test B
exitcode="$?"

if [ "$exitcode" != 0 ] ; then
	echo >&2 "*** wrong exit code"
	exit 1
fi

if [ ! -r B ] ; then
	echo >&2 "*** B was not rebuilt"
	exit 1
fi

#
# Step 3:  stu A:  A is rebuilt.
#

../../sh/touch_old A 2 || exit 1
../../sh/touch_old B 1 || exit 1
../../sh/touch_old C 2 || exit 1

../../stu.test A >list.out
exitcode="$?"

if [ "$exitcode" != 0 ] ; then
	echo >&2 "*** wrong exit code"
	exit 1
fi

if [ A -ot B ] ; then
	echo >&2 "*** A is older than B"
	exit 1
fi

if grep -qiF 'Nothing to be done' list.out ; then
	echo >&2 "*** must not output 'Nothing to be done'"
	exit 1
fi

exit 0
