#! /bin/sh

preload_tty_so=$(cd ../.. ; pwd)/bin/preload-tty.so
CMDPREFIX_TTY="TERM=xterm"
LD_PRELOAD_VALUE_TTY="$preload_tty_so"

( cd ../.. ; sh/ccpreload src/preload-tty.cc bin/preload-tty.so ; ) || exit 2

rm -f ? || exit 2

eval $CMDPREFIX_TTY LD_PRELOAD=$LD_PRELOAD_VALUE_TTY ../../bin/stu.test \
	-q -F "'A={Hello}'" A \>list.all 2\>\&1
exitstatus=$?

[ "$exitstatus" = 1 ] || {
	echo >&2 "*** Exit code wrong"
	exit 1
}

cmp -s list.all stdall || {
	diff list.all stdall
	echo >&2 "*** Output"
	echo >&2 stdout+stderr:
	echo >&2 _____________
	cat  >&2 list.all
	echo >&2 _____________
	echo >&2 expected:
	echo >&2 _____________
	cat  >&2 stdall
	echo >&2 _____________
	exit 1
}

exit 0
