#! /bin/sh

set -e

rm -f ?

../../sh/touch_old A
touch B

../../stu.test >list.out 2>list.err

grep -qF 'Nothing to be done' list.out || {
	echo >&2 "*** Missing 'Nothing to be done'"
	exit 1
}

exit 0
