#! /bin/sh

set -e

rm -f ?

../../sh/touch_old A
touch B

../../stu.test >list.out 2>list.err

grep -qFx 'Targets are up to date' list.out || {
	echo >&2 "*** Missing 'Targets are up to date'"
	exit 1
}

exit 0
