#! /bin/sh

rm -f A || exit 2

../../bin/stu.test -K >list.out 2>list.err &
pid=$!

sleep 1 || exit 2

kill -TERM "$pid"
wait "$pid" 2>/dev/null
exitstatus=$?

# 143 = 128 + 15.  15 is the POSIX-mandated value of SIGTERM.
[ "$exitstatus" = 143 ] || {
	echo >&2 '*** Exit status must be 143, but is not'
	echo >&2 "exitstatus='$exitstatus'"
	exit 1
}

[ -s A ] || {
	echo >&2 "*** The file 'A' must exist and have size larger than zero"
	exit 1
}

lines=$(echo $(cat A | wc -l))

[ "$lines" = 2 ] || {
	echo >&2 "*** File 'A' must contain exactly two lines"
	exit 2
}

exit 0
