#!/bin/sh
. ../../sh/test.sh

mkdir list.dir
cd list.dir

{
	printf 'aaa\0'
	printf 'bbb\0'
	printf ':::\0'
	printf '   \0'
	printf '\t\t\t\0'
	printf ')(\0'
	printf '"'"'"'\0'
	printf 'ccc\0'
	printf '%s\0' '-'
} >list.FILES

../../../bin/stu.test -0 list.FILES -F '$name = {correct}' >list.out 2>list.err

tr '\0' '\n' <list.FILES >list.n

while IFS= read -r file ; do
	echo >&3 "file='$file'"
	[ -r "$file" ]
	grep -q -F -x -e 'correct' <"$file"
done <list.n
