#!/bin/sh
. ../../sh/test.sh

do_rm()
{
	rm -f aaa bbb ccc list.FILES
	rm -f :::
	rm -f '   '
	rm -f "$(printf '\t\t\t')"
	rm -f ')('
	rm -f '"'"'"
	rm -f --  '-'
}

do_rm

{
	printf 'aaa\0'
	printf 'bbb\0'
	printf ':::\0'
	printf '   \0'
	printf '\t\t\t\0'
	printf ')(\0'
	printf '"'"'"'\0'
	printf 'ccc\0'
	printf -- '-\0'
} >list.FILES

../../bin/stu.test -0 list.FILES -F '$name = {correct}' >list.out 2>list.err

IFS=
cat list.FILES | while read -r file ; do
	[ -r "$file" ] || Error "file '$file' not created"
	<"$file" grep -qF correct || Error "file '$file' has invalid content"
done

do_rm
