#! /bin/sh

set -e

rm -f ?

../../stu.test >list.out 2>list.err

[ -e B ] || { echo >&2 "*** (1) 'B' must exist" ; exit 1 ; }
grep -qF bbb A || { echo >&2 "*** (1) 'A' must contain 'bbb'" ; exit 1 ; }

../../sh/touch_old A 2
echo ddd >B

../../stu.test >list.out 2>list.err

grep -qF 'cp B A' list.out || {
	echo >&2 "*** (2) command for 'A' must be executed"
	echo "output:"
	echo ________
	cat list.out
	echo ________
	exit 1
}

grep -qF ddd A || {
	echo >&2 "*** (2) 'A' must contain 'ddd'"
	exit 1
}

exit 0
