#! /bin/sh

rm -f ? || exit 2

echo ../../bin/stu.test 
../../bin/stu.test >stdout-correct

rm -f ? || exit 2

echo ../../bin/stu.test -M Hello
../../bin/stu.test -M Hello >list.out
exitstatus=$?

if [ "$exitstatus" != 0 ] ; then
	echo '*** (A)'
	exit 1
fi

diff list.out stdout-correct && {
	echo '*** (B)'
	exit 1
}

diff out output-correct || {
	echo '*** (C)'
	exit 1
}

# Check that two invocations do not give the same order

rm -f ? || exit 2

echo ../../bin/stu.test -M Hello
../../bin/stu.test -M Hello >list.out2
exitstatus=$?

if [ "$exitstatus" != 0 ] ; then
	echo '*** (A2)'
	exit 1
fi

# The two runs *must* have identical order 
diff list.out list.out2 || {
	echo '*** (B2)'
	exit 1
}

diff out output-correct || {
	echo '*** (C2)'
	exit 1
}

rm -f out list.* stdout-correct || exit 2

exit 0
