#!/bin/sh
# TOPIC: %include a/ ; a/ exists but not a/main.stu
. ../../sh/test.sh

mkdir ddd.data

set +e
../../bin/stu.test >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 1 ]
grep -q -F -e 'main.stu:4:10: %include "ddd.data/main.stu": ' list.err
