#! /bin/sh
#
# Run all tests that fail, and show their output.  Used to visually
# inspect color ouput, to see whether it looks nice.  This is in
# addition to unit tests that check whether output is correct.
#
# PARAMETERS
#	(optional) Names of tests, like for sh/test
#
# STDOUT
#	The output and error output of the tests, including color
#	codes.  Can for instance be piped into less -R to see all.
#

preload_tty_so=$PWD/bin/preload-tty.so
CMDPREFIX_TTY="TERM=xterm"
LD_PRELOAD_VALUE_TTY="$preload_tty_so"

sh/ccpreload src/preload-tty.cc bin/preload-tty.so || exit 2

rm -f bin/stu.test || exit 2
if [ "$NDEBUG" ] ; then
	ln -s stu bin/stu.test || exit 2
else
	ln -s stu.debug bin/stu.test || exit 2
fi

cd tests

if [ "$1" ] ; then
	tests="$@"
else
	tests=$(echo *)
fi

for file in $tests
do
	file=$(echo "$file" | sed -e 's,^tests/,,')
	if [ ! -d "$file" ]; then
		echo >&2 "$0: *** '$file' is not a directory"
		error=1
		echo "$file" >&6
		errors=1
		continue
	fi

	cd "$file"
	if [ -r EXITSTATUS ] && ! [ -r NOTTY ] && ! [ -r PRELOAD.cc ] ; then
		../../sh/rm_tmps || exit 2
		CMD=
		if [ -r CMD ]; then
			CMD=$(sed -e '/^[[:space:]]*$/d' <CMD)
		fi
		echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		echo "~~~~~~~~~~~ $file"
		echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		echo
		eval $CMDPREFIX_TTY LD_PRELOAD=$LD_PRELOAD_VALUE_TTY \
			../../bin/stu.test "$CMD" 2\>\&1
		echo
		../../sh/rm_tmps || exit 2
	fi
	cd ..
done

echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
exit 0
