#! /bin/sh
#
# Delete temporary files created by tests.  The tests only create
# temporary files of these patterns.  Executed within each test
# directory.  Any of such named files may be directories. 
#
# NOTE:   *don't* execute this in stu/, because we have the files 'sh'
# and 'dep.hh' there.  
#

rm -Rf -- ? ?? list.* A.* *.data dep.* .+-~_ 
