#!/bin/sh
set -e

[ "$INSTALL_VERBOSE" ] && exec 3>&2 || exec 3>/dev/null

prefix=${prefix:-/usr/local}
echo >&3 "Installing in $prefix"

mkdir -p "$prefix"/bin
mkdir -p "$prefix"/man/man1
install bin/stu   "$prefix"/bin/stu
install man/stu.1 "$prefix"/man/man1/stu.1
