#! /bin/sh

[ "$1" ] || {
	echo >&2 "*** Invocation: $0 FILE..."
	exit 1
}

error=0

for file in "$@"
do
	if [ -h "$file" ] ; then
		echo "Replacing '$file'"
		source="$(readlink "$file")"
		rm -- "$file" && cp -- "$source" "$file" || {
			echo >&2 "*** Error replacing '$file'"
			error=1
		}
	else
		: # The file has already been replaced 
	fi
done

exit $error
