#! /bin/sh
#
# Remove temporary files created by tests.  The tests only create temporary files of these
# patterns.  Executed within each test directory.  Any such named files may be
# directories.
#
# None of the patterns matches any file that we would create within the main stu/
# directory, so we can safely call this to remove junk files created while debugging.  In
# particular, all one-letter and two-letter files are deleted except 'sh'.
#

## TODO rename rm_tmp

rm -Rf -- ? list.* A.* ./*.data x.* *SCHTROUMPF* .+-~_ || exit 1

for file in ?? ; do
	if [ "$file" = sh ] ; then continue ; fi
	rm -f -- "$file" || exit 1
done
