#!/bin/sh
#
# Remove temporary files created by tests.  The tests only create temporary files of these
# patterns.  Executed within each test directory.  Any such named files may be
# directories.
#
# Kept in sync with .gitignore.
#
# When called without arguments, do not delete 'sh', otherwise, do delete it.
#
# INVOCATION
#    $0 [DIR]...
#

SCRIPT=$0

# Due to use of rm unquoted $@ and xargs, patterns must not contain any of the characters
# in the set { ' " \ }.  Characters * and ? can only be used as glob patterns.
patterns='
?
??
list.*
A.*
*.data
x.*
*SCHTROUMPF*
.+-~_
*abcdef
'

if [ "$1" = --delete ] ; then
	shift
	rm -R -f -- $@
	exit
fi

Remove_Files_Slow()
{
	rm -Rf -f ? list.* A.* *.data x.* *SCHTROUMPF* .+-~_ *abcdef || exit 1
	for file in ?? ; do
		[ "$file" = sh ] && continue
		rm -R -f -- "$file" || exit 1
	done
}

Remove_Files_Fast() # [DIR]...
{
	printf '%s\n' "$@" |
	while IFS= read -r dir ; do
		printf '%s' "$patterns" | while IFS= read -r pattern ; do
			[ "$pattern" ] || continue
			printf '%s/%s\0' "$dir" "$pattern"
		done
	done |
	xargs -0 "$SCRIPT" --delete
}

if [ $# = 0 ] ; then
	Remove_Files_Slow
else
	Remove_Files_Fast "$@"
fi
