#! /bin/sh
#
# Setup the Auto toolchain.
#
# Many dirty things happen here. 
#

rm -Rf Makefile Makefile.in Makefile.in.bak configure config.log config.status autom4te.cache 
mkdir -p build-aux
aclocal
automake --add-missing
cp Makefile.in Makefile.in.orig

export sed_cxxflags='s, -g , ,;s, -DPACKAGE_STRING=\\\\"[^"]*\\\\" , ,;s,\\\\",",g'

{
	sed -E <Makefile.in.orig -e '

/^stu\$/,+2d
/^\.cc\.o/,+6d

s,stu\.cc,src/stu.cc,g
s,stu.\$\(OBJEXT\),bin/stu.$(OBJEXT),g
s,stu\$\(EXEEXT\),bin/stu$(EXEEXT),g
'
	echo
	printf 'bin/stu:  src/stu.cc $(stu_DEPENDENCIES) $(EXTRA_stu_DEPENDENCIES)\n'
	printf '	mkdir -p bin\n'
	printf '	$$(echo '\''$(CXXCOMPILE)'\'' " " | sed -E -e '\'"$sed_cxxflags"\'') src/stu.cc -o bin/stu\n'
} >Makefile.in

rm Makefile.in.orig
autoconf -Im4
sh/replacelinks build-aux/*
./configure
touch all-auto
