#! /bin/sh
#
# Check that source files do not contain certain patterns used for
# temporary comments used during development of Stu.  These include:
# '//' (for C++ code), '#''#' (for shell scripts or Stu files), 'XX''X'
# (for some source files), tabs in the manpage.
#

ret=0

#
# // in C++ files
#

grep -E '(^|[^:])//' *.cc *.hh && {
	echo >&2 "*** C++ source files must not contain //"
	ret=1
}

#
# Double # in script files 
#

find . -type f -a \( -name '*.stu' -o -perm -u+x -o -name Makefile.devel \) -a \! -name '*~' \
	-a \! -path './.git*' -a \! -path './stu.*' -a \! -path './stu' \
	-a \! -path './config*' -a \! -path './build-aux/*' -a \! -path ./TODO.stu | 
xargs grep -lF '#''#' && {
	echo >&2 "*** Shell scripts, makefiles and Stu scripts must not contain #""#"
	ret=1
}

#
# 'XX''X'
#

grep -F XX''X NEWS stu.1.in stu.cc *.hh sh/* && {
	echo >&2 "*** Certain files must not contain 'XX""X'"
	ret=1
}

#
# Tab in manpage source
#

grep -F "$(printf '\t')" stu.1.in && {
	echo >&2 "*** 'stu.1.in' must not contain tabs"
	ret=1
}

exit "$ret"
