#! /bin/sh
#
# Test that both lists of options are the same.
#

ret=0

file_src=src/options.hh
file_man=man/stu.1.in

<"$file_src" sed -e '/^[[:space:]]*" *-[0-9a-zA-Z]/!d;s,^[^-]*-\(.\).*$,\1,' >test_options.a || exit 2
<"$file_man" sed -e '/^[[:space:]]*\.IP[[:space:]]\{1,\}"\{0,1\}-./!d;s/^[[:space:]]*\.IP[[:space:]]\{1,\}"\{0,1\}-\(.\).*$/\1/' >test_options.b || exit 2

if ! cmp test_options.a test_options.b ; then
	echo >&2 "$0: *** The options given and '$file_src' are different from those given in '$file_man'"
	echo >&2 "Options from '$file_src':"
	cat >&2 test_options.a
	echo >&2 "Options from '$file_man':"
	cat >&2 test_options.b
	echo >&2 "Diff:"
	diff test_options.a test_options.b
	ret=1
fi

rm -f test_options.a test_options.b || exit 2
exit $ret
