#! /bin/sh
#
# Check that we don't use 'sed -r'.  
#
# Background:  'sed -r' is a GNU extension that enabled extended regular
# expressions.  POSIX does not prescribe a "extended regexp" mode for
# sed.  In many implementations, '-E' does the same.  '-E' is more
# portable than '-r', but still not POSIX. 
#

find_sed() {
	find . -type f -a \! -path './.git*' -a \! -name '*~' | xargs grep -lE -- 'sed[[:space:]]+-re'
}

count="$(echo $(find_sed | wc -l))"

[ "$count" = 0 ] || {
	echo >&2 "*** 'sed -r' must not be used:"
	echo >&2 === BEGIN
	find_sed
	echo >&2 === END
	exit 1
}

exit 0
