#! /bin/sh
#
# Check that we don't use 'sed -r'. 
#

find_sed() {
	find . -type f -a \! -path './.git*' -a \! -name '*~' | xargs grep -lE -- 'sed[[:space:]]+-re'
}

count="$(echo $(find_sed | wc -l))"

[ "$count" = 0 ] || {
	echo >&2 "*** 'sed -r' must not be used:"
	echo >&2 === BEGIN
	find_sed
	echo >&2 === END
	exit 1
}

exit 0
