#!/bin/sh
#
# Print list of all tests and their topic.  The topic is included in each test's main.stu
# or EXEC file, or in a separate TOPIC file.
#
# This is a work in progress, and not yet integrated into 'make test'.
#
# LETTERS
#	a - File/phony
#       p - Parameter
#       v - Environment variable
#

set -e

mkdir -p ../log
exec 4>log/topic

cd tests

ls -1U | ../sh/sort_tests | while IFS= read -r test ; do
	if ! topic=$(cat "$test"/TOPIC 2>/dev/null) ; then
		files=
		[ -e "$test"/EXEC ] && files="$files $test/EXEC"
		[ -e "$test"/main.stu ] && files="$files $test/main.stu"
		topic=$(sed -E -e 's,^.*TOPIC:\s*(.*)$,\1,
t
d' $files /dev/null)
	fi
	[ "$topic" ] || topic='<missing>'
	printf >&4 '%-16s %s\n' "$test" "$topic"
done
