#! /bin/sh
#
# Simulate a TTY:  Execute the given COMMAND as if in a TTY. 
#
# INVOCATION 
#
#	sh/tty COMMAND
#
# REQUIREMENTS
#
#	expect
#

#\
export TERM=xterm

# The next line is executed by sh, but not by tclsh \
exec tclsh "$0" ${1+"$@"}

package require Expect

set stty_init "-opost"
set timeout -1
eval [list spawn -noecho] $argv
expect
exit [lindex [wait] 3]
