#! /bin/sh
#
# Simulate a TTY
#

# The next line is execute by sh, not by tcl \
exec tclsh8.6 "$0" ${1+"$@"}

package require Expect

set stty_init "-opost"
set timeout -1
eval [list spawn -noecho] $argv
expect
exit [lindex [wait] 3]
