#! /bin/sh

rm -f ? || exit 2

echo ../../bin/stu.test
../../bin/stu.test
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo "*** (a)"
	exit 1
}

rm -f B C || exit 2

echo ../../bin/stu.test
../../bin/stu.test >list.out
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo "*** (b)"
	exit 1
}

grep -Fq 'cat D E' list.out && {
	echo "*** (c)"
	exit 1
}

exit 0
