#! /bin/sh

doo() { echo "$@" ; "$@" ; }

for CMD in "" "-j2" "-j 3" ; do

	doo rm -f ?

	../../bin/stu.test $CMD -k >list.out 2>list.err
	exitstatus=$?

	[ "$exitstatus" = 1 ] || {
		echo >&2 "$0:  *** Exit status was $exitstatus instead of 1"
		exit 1
	}

	if [ ! -r C -o ! -r E ]; then
		echo >&2 "$0:  *** 'C' and 'E' were not created"
		exit 1
	fi
done

rm -f ? || exit 2

exit 0
