#! /bin/sh

rm -f ? || exit 2

#
# Step 1:  build A:  everything is built
#

../../bin/stu.test
exitstatus=$?

if [ "$exitstatus" != 0 ] ; then
	echo >&2 "*** Wrong exit code"
	exit 1
fi

if [ ! -r A -o ! -r B -o ! -r C ] ; then
	echo >&2 "*** A/B/C were not built"
	exit 1
fi

#
# Step 2:  rm B; stu B:  B is re-built
#

rm B || exit 2
../../sh/touch_old A 1 || exit 2
../../sh/touch_old C 1 || exit 2

../../bin/stu.test B
exitstatus=$?

if [ "$exitstatus" != 0 ] ; then
	echo >&2 "*** wrong exit code"
	exit 1
fi

if [ ! -r B ] ; then
	echo >&2 "*** B was not rebuilt"
	exit 1
fi

#
# Step 3:  stu A:  A is rebuilt.
#

../../sh/touch_old A 2 || exit 2
../../sh/touch_old B 1 || exit 2
../../sh/touch_old C 2 || exit 2

../../bin/stu.test A >list.out
exitstatus=$?

if [ "$exitstatus" != 0 ] ; then
	echo >&2 "*** Exit status incorrect"
	exit 1
fi

if [ A -ot B ] ; then
	echo >&2 "*** A is older than B"
	exit 1
fi

if grep -Fqi 'Nothing to be done' list.out ; then
	echo >&2 "*** must not output 'Nothing to be done'"
	exit 1
fi

exit 0
