#!/bin/sh
. ../../sh/test.sh

FILE_SO=../../bin/preload.so
dir=$(pwd)
( cd ../.. && sh/ccpreload "$dir"/PRELOAD.cc "$dir"/"$FILE_SO" ; )

echo >&3 ../../bin/stu.test -i '&'
LD_PRELOAD=$FILE_SO ../../bin/stu.test -i >list.out 2>list.err & pid=$!

echo >&3 sleep 1
sleep 1

child_pid=$(sed -E -e 's,^pid=,,
t
d' list.out)
echo >&3 child_pid="$child_pid"
echo "$child_pid" | grep -q -E -x -e '[0-9]+'

echo >&3 kill -s STOP "$child_pid"
kill -s STOP "$child_pid"

echo >&3 sleep 1
sleep 1

echo >&3 kill -s TERM "$child_pid"
kill -s TERM "$child_pid"

echo >&3 kill -s TERM "$pid"
kill -s TERM "$pid"

set +e
wait "$child_pid" 2>/dev/null
exitstatus_child=$?
set -e
echo >&3 exitstatus_child=$exitstatus_child

set +e
wait "$pid" 2>/dev/null
exitstatus=$?
set -e
echo >&3 exitstatus=$exitstatus

[ "$exitstatus" = 143 ]

grep -q -F -e 'tcsetpgrp: ' list.err
