#!/bin/sh
. ../../sh/test.sh

preload_tty_so=$(cd ../.. ; pwd)/bin/preload-tty.so
CMDPREFIX_TTY="TERM=xterm"
LD_PRELOAD_VALUE_TTY="$preload_tty_so"

( cd ../.. ; sh/ccpreload src/preload-tty.cc bin/preload-tty.so ; )

touch A

eval $CMDPREFIX_TTY LD_PRELOAD=$LD_PRELOAD_VALUE_TTY ../../bin/stu.test A \>list.all 2\>\&1

cmp -s list.all stdall || Error 'output'
