#!/bin/sh
. ../../sh/test.sh

rm -f stderr

set +e
../../bin/stu.test -C '%version 0.9' >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 2 ] || Error 'exit status'

VERSION=$(cat ../../VERSION)
<stderr-in >list.stderr sed -e 's,\$VERSION,'"$VERSION"',g'

diff list.err list.stderr || {
	echo >&2 '*** list.stderr'

	echo >&2 "'list.stderr'":
	echo >&2 _____
	cat >&2 list.stderr
	echo >&2 _____

	echo >&2 "'list.err'":
	echo >&2 _____
	cat >&2 list.err
	echo >&2 _____

	exit 1
}
