#! /bin/sh
#
# Trivial dependencies.
#
# * (0) stu
#	* B and A are built
# * (1) touch C
# * stu
#	* nothing is done
# * (2) touch D
# * stu
#	* nothing is done
# * (3) rm D
# * stu
#	* nothing is done
# * (4) touch B
# * stu
#	* D, C and A are rebuilt
# * (5) touch B
# * stu
#	* A is rebuilt
# 

set -e

rm -f ?

#
# (0) 
#

../../stu.test >list.out 2>list.err

diff list.out stdout-0 || { echo >&2 '*** (0) Stdout' ; exit 1 ; }
[ -r list.err ] && [ ! -s list.err ] || { echo >&2 '*** (0) Stderr' ; exit 1 ; }
[ -r A ] || { echo >&2 "*** (0) A" ; exit 1 ; }
[ -r B ] || { echo >&2 "*** (0) B" ; exit 1 ; }

#
# (1)
#

../../sh/touch_old A 2
../../sh/touch_old B 2
touch C

../../stu.test >list.out 2>list.err

diff list.out stdout-1 || { echo >&2 '*** (1) Stdout' ; exit 1 ; }
[ -r list.err ] && [ ! -s list.err ] || { echo >&2 '*** (1) Stderr' ; exit 1 ; }

#
# (2)
#

../../sh/touch_old A 2
../../sh/touch_old B 2
../../sh/touch_old C 2
touch D

../../stu.test >list.out 2>list.err

diff list.out stdout-2 || { echo >&2 '*** (2) Stdout' ; exit 1 ; }
[ -r list.err ] && [ ! -s list.err ] || { echo >&2 '*** (2) Stderr' ; exit 1 ; }

#
# (3) 
#

../../sh/touch_old A 2
../../sh/touch_old B 2
../../sh/touch_old C 2
rm D

../../stu.test >list.out 2>list.err

diff list.out stdout-3 || { echo >&2 '*** (3) Stdout' ; exit 1 ; }
[ -r list.err ] && [ ! -s list.err ] || { echo >&2 '*** (3) Stderr' ; exit 1 ; }

#
# (4)
#

../../sh/touch_old A 2
../../sh/touch_old C 2
touch B

../../stu.test >list.out 2>list.err

diff list.out stdout-4 || {
	echo >&2 "*** (4) Stdout"
	echo list.out:
	echo ________
	cat list.out
	echo ________
	echo stdout-4
	echo ________
	cat stdout-4
	echo ________
	exit 1
}
[ -r list.err ] && [ ! -s list.err ] || { echo >&2 '*** (4) Stderr' ; exit 1 ; }
[ -r D ] || { echo >&2 "*** (4) D" ; exit 1 ; }

#
# (5)
#

../../sh/touch_old A 2
../../sh/touch_old C 2
../../sh/touch_old D 2
touch B

../../stu.test >list.out 2>list.err

diff list.out stdout-5 || { echo >&2 '*** (5) Stdout' ; exit 1 ; }
[ -r list.err ] && [ ! -s list.err ] || { echo >&2 '*** (5) Stderr' ; exit 1 ; }

exit 0
