#!/bin/sh
. ../../sh/test.sh

preload_tty_so=$(cd ../.. ; pwd)/bin/preload-tty.so
CMDPREFIX_TTY="TERM=xterm"
LD_PRELOAD_VALUE_TTY="$preload_tty_so"

( cd ../.. ; sh/ccpreload src/preload-tty.cc bin/preload-tty.so ; )

rm -f ?

set +e
eval $CMDPREFIX_TTY LD_PRELOAD=$LD_PRELOAD_VALUE_TTY ../../bin/stu.test \
	-q -F "'A={Hello}'" A \>list.all 2\>\&1
exitstatus=$?
set -e

[ "$exitstatus" = 1 ] || Error 'exit status'

cmp -s list.all stdall || Error 'output'
