#! /bin/sh

doo() { echo "$@" ; "$@" ; }

kill_sleeps() 
{
	for pid in $(ps -fA | grep 31415926535 | grep -v grep | sed -e 's/^[^[:space:]]\{1,\}[[:space:]]\{1,\}\([0-9]\{1,\}\)[[:space:]].*$/\1/') ; do
		echo "$0:  Killing PID '$pid'"
		kill "$pid"
	done

	count="$(echo $(ps -fA | grep 31415926535 | grep -v grep | wc -l))"
	[ "$count" = 0 ] || {
		echo >&2 '*** Could not kill all processes'
		echo >&2 "count='$count'"
		echo >&2 'Still running:'
		ps -fA | grep 31415926535 | grep -v grep
		exit 1
	}
}

doo rm -f ?

kill_sleeps

# Make sure no process is running
if [ "$(echo $(ps -fA | grep 31415926535 | grep -v grep | wc -l))" != 0 ]; then
	echo >&2 "$0:  *** There is already a process running:" 
	ps -fA | grep 31415926535 | grep -v grep >&2
	exit 1
fi

# Start Stu 
../../stu.test -k -j99 >list.out 2>list.err &
PID=$!

# Sleep so that there is time for Stu to start all processes  
doo sleep 1

# Terminate Stu
doo kill -TERM $PID

# Give Stu time to kill all processes
doo sleep 1

# Make sure no process is still running
if [ "$(echo $(ps -fA | grep 31415926535 | grep -v grep | wc -l))" != 0 ]; then
	echo >&2 "$0:  *** There is still a process running:" 
	ps -fA | grep 31415926535 | grep -v grep >&2
	exit 1
fi

# Make sure all files were deleted
for file in A B C D E F G H I J K L M N O P Q R S T U V W X Y Z ; 
do
	if [ -r $file ]; then
		echo >&2 "$0:  *** File '$file' should not have been created"
		exit 1
	fi
done

doo rm -f ?

kill_sleeps
