#! /bin/sh

doo() { echo "$@" ; "$@" ; }

kill_sleeps() 
{
    for pid in $(ps -fe | grep 31415926535 | grep -v grep | sed -re 's,^\S+\s+([0-9]+)\s.*$,\1,') ; do
	echo >&2 "$0:  *** Killing PID '$pid'"
	kill "$pid"
    done
}

doo rm -f ?

kill_sleeps

# Make sure no process is running
if [ "$(ps -fe | grep 31415926535 | grep -v grep | wc -l)" != 0 ]; then
    echo >&2 "$0:  *** There is already a process running:" 
    ps -fe | grep 31415926535 | grep -v grep >&2
    exit 1
fi

# Start Stu 
echo ../../stu -k -j99
../../stu -k -j99 &
PID=$!
# echo "PID=»$PID«"

# Sleep so that there is time for Stu to start all processes  
doo sleep 1

# Terminate Stu
doo kill -TERM $PID

# Give Stu time to kill all processes
doo sleep 1

# Make sure no process is still running
if [ "$(ps -fe | grep 31415926535 | grep -v grep | wc -l)" != 0 ]; then
    echo >&2 "$0:  *** There is still a process running:" 
    ps -fe | grep 31415926535 | grep -v grep >&2
    exit 1
fi

# Make sure all files were deleted
for file in A B C D E F G H I J K L M N O P Q R S T U V W X Y Z ; 
do
    if [ -r $file ]; then
	echo >&2 "$0:  *** File '$file' should not have been created"
	exit 1
    fi
done

doo rm -f ?

kill_sleeps
