#!/bin/sh
. ../../sh/test.sh

rm -f ?

set +e
STU_SHELL=./shell ../../bin/stu.test >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 0 ] || Error 'exit status'
diff list.out stdout-correct || Error 'stdout'
