#! /bin/sh
#
# Empty argument to -C
#

rm -f ?

../../stu -C '' >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 4 ] || {
	echo >&2 '*** exit code'
	exit 1
}

cmp list.err stderr || {
	echo >&2 '*** stderr'
	echo >&2 list.err:
	echo >&2 ______
	cat >&2 list.err
	echo >&2 ______
	exit 1
}

exit 0
