#!/bin/sh
. ../../sh/test.sh

rm -f ?

#
# Build for the first time
#

../../bin/stu.test

[ -h W ] || Error 'W'

#
# Remove 'D'
#

../../sh/touch_old A 2
../../sh/touch_old B 2
../../sh/touch_old C 2
rm D

#
# Build for a second time
#

../../bin/stu.test

exit 0
