#! /bin/sh

../../bin/stu.test -i -j2 >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 4 ] || {
	echo >&2 "*** Expected exit status 4, not $exitstatus"
	exit 1
}

grep -qF "Option -i: parallel mode using '-j' cannot be used in interactive mode" list.err || {
	echo >&2 "*** Expected the correct error message"
	exit 1
}

exit 0
