#! /bin/sh

../../stu.test -i -j2 >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 4 ] || {
	echo >&2 "*** Expected exit code 4, not $exitcode"
	exit 1
}

grep -qF "Option -i: parallel mode using '-j' cannot be used in interactive mode" list.err || {
	echo >&2 "*** Expected the correct error message"
	exit 1
}

exit 0
