#!/bin/sh
. ../../sh/test.sh

rm -Rf xxx
mkdir xxx

set +e
../../bin/stu.test >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 2 ] || Error 'exit status'
grep -q -F -e "xxx/../main.stu:5:10: recursive inclusion of \"xxx/../main.stu\"" list.err ||
	Error 'stderr'
rm -Rf xxx list.*
