#! /bin/sh

doo() { echo "$@" ; "$@" ; }

doo rm -f ?

echo ../../stu.test
../../stu.test -k >list.out 2>list.err
exitcode="$?"
if [ "$exitcode" != 1 ] ; then
	echo >&2 "$0:  *** Stu did not fail (run A)"
	exit 1
fi

grep -qF 'not exist' list.err && {
	echo "$0:  *** Error output not correct (run A)"
	exit 1
}

doo rm -f ?

echo ../../stu.test -k
../../stu.test -k >list.out 2>list.err
exitcode="$?"
if [ "$exitcode" != 1 ] ; then
	echo >&2 "$0:  *** Stu did not have exit code 1 (run B)"
	exit 1
fi

grep -Fq CORRECT B || {
	echo >&2 "$0:  *** File 'B' not correctly built (run B)"
	exit 1
}

grep -qF "no rule to build 'nonexistingfile'" list.err || {
	echo "$0:  *** Error output does not contain \"no rule to build 'nonexistingfile'\" (run B)"
	exit 1
}

grep -qF 'Targets not up to date because of errors' list.err || {
	echo "$0:  *** error output does not contain 'Targets not up to date because of errors' (run B)"
	exit 1
}

exit 0
