#!/bin/sh
. ../../sh/test.sh

rm -f ?

set +e
../../bin/stu.test >list.out 2>list.err
exitstatus="$?"
set -e

[ "$exitstatus" = 1 ] || Error 'exit status'
[ -e A ] && Error 'A was not removed'

exit 0
