#! /bin/sh

set -e

do_rm() {
	rm -f aaa bbb ccc FILES
	rm -f :::
	rm -f '   '
	rm -f "$(printf '\t\t\t')"
	rm -f ')('
	rm -f '"'"'"
	rm -f --  '-'
}

do_rm

{
	printf 'aaa\0'
	printf 'bbb\0'
	printf ':::\0'
	printf '   \0'
	printf '\t\t\t\0'
	printf ')(\0'
	printf '"'"'"'\0'
	printf 'ccc\0'
	printf -- '-\0'
} >FILES

../../stu.test -0 FILES -F '$name = {correct}' >list.out 2>list.err

IFS=
cat FILES | while read -r file ; do
	[ -r "$file" ] || {
		echo >&2 "*** File '$file' not created"
		exit 1
	}
	<"$file" grep -qF correct || {
		echo >&2 "*** File '$file' has invalid content"
		exit 1
	}
done

do_rm

exit 0
