#!/bin/sh
#
# The output of "stu -h" does not contains tabs.
#

. ../../sh/test.sh

../../bin/stu.test -h >list.out 2>list.err

[ -e list.err ] || Error A
[ -s list.err ] && Error B
[ -e list.out ] || Error C
[ -s list.out ] || Error D

grep -q -v -F -e "$(printf '\t')" list.out || Error E
