#! /bin/sh
#
# A reminder:  use
#
#    rm -- FILE
#
# to remove files with ANY possible name. 
#

rm -f -- A -r -s || exit 1

../../stu.test >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** Exit code"
	exit 1
}

[ -r list.err ] && ! [ -s list.err ] || {
	echo >&2 "*** Error output"
	echo >&2 list.err:
	echo >&2 _______________
	cat  >&2 list.err
	echo >&2 _______________
	exit 1
}

grep -qxF "cp '-s' '-r'" list.out || {
	echo >&2 "*** Output"
	exit 1
}

[ -r A ] && grep -qxF correct A || {
	echo >&2 "*** Content of 'A'"
	exit 1
}

rm -f -- A -r -s || exit 1

exit 0
