#! /bin/sh

../../bin/stu.test -P >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo >&2 '*** Exit status'
	exit 1
}

[ -r list.err ] && [ ! -s list.err ] || {
	echo >&2 '*** stderr'
	exit 1
}

grep -qF 'list.${name}' list.out || {
	echo >&2 '*** stdout'
	exit 1
}

exit 0
