#! /bin/sh

doo() { echo "$@" ; "$@" ; }

kill_sleeps() 
{
	for pid in $(ps -fA | grep 31415926535 | grep -v grep | sed -e 's/^[^[:space:]]\{1,\}[[:space:]]\{1,\}\([0-9]\{1,\}\)[[:space:]].*$/\1/') ; do
		echo >&2 "$0:  *** Killing PID '$pid'"
		kill "$pid"
	done

	# The extra echo in the next line is to get rid of whitespace
	count="$(echo $(ps -fA | grep 31415926535 | grep -v grep | wc -l))"
	[ "$count" = 0 ] || {
		echo >&2 '*** Could not kill all processes'
		echo >&2 "count='$count'"
		echo >&2 'Still running:'
		ps -fA | grep 31415926535 | grep -v grep
		exit 1
	}
}

doo rm -f ?

doo kill_sleeps

echo '../../stu.test -z >list.out 2>list.err &'
../../stu.test -z >list.out 2>list.err &
pid="$!"

# Make sure the target 'X' is finished 
doo sleep 1

doo kill -TERM "$pid"

# Give Stu time to kill all processes
doo sleep 1

# Make sure no process is still running
if [ "$(echo $(ps -fA | grep 31415926535 | grep -v grep | wc -l))" != 0 ]; then
	echo >&2 "$0:  *** There is still a process running:" 
	ps -fA | grep 31415926535 | grep -v grep >&2
	exit 1
fi

# Check that statistics are not output

grep -qF 'STATISTICS' list.out && {
	echo >&2 '*** Number of jobs started'
	echo >&2 stdout:
	echo >&2 ____
	cat >&2 list.out
	echo >&2 ____
	exit 1
}

grep -qF 'STATISTICS' list.err && {
	echo >&2 '*** Number of jobs started'	
	echo >&2 stderr:
	echo >&2 ____
	cat >&2 list.err
X	echo >&2 ____
	exit 1
}

doo kill_sleeps

exit 0
