#! /bin/sh

../../bin/stu.test -f - <<EOF >list.out 2>list.err
:::: # Syntax error
EOF
exitstatus="$?"

[ "$exitstatus" = 2 ] || {
	echo >&2 "*** Exit status"
	exit 1
}

grep -qF '<stdin>' list.err || {
	echo >&2 "*** Missing '<stdin>'"
	exit 1
}

exit 0
