#! /bin/sh

# $1:  the character to insert
# $2:  the error output
test_one()
{
	char=$1
	output=$2

	echo "CASE: ($char|$output)"

	rm -f ? list.* main.stu || exit 2

	echo "A: list.x { touch A } list.\${xxx${char}yyy\} { touch \"list.\${xxx${char}yyy\}\" }" >main.stu || exit 2

	../../bin/stu.test >list.out 2>list.err
	exitstatus=$?

	[ "$exitstatus" = 2 ] || {
		echo >&2 "*** [$output] Exit status is not 2"
		exit 1
	}

	[ -r list.out ] && [ ! -s list.out ] || {
		echo >&2 "*** [$output] Wrong output"
		exit 1
	}

	grep -qF "character \"$output\" must not appear" list.err || {
		echo >&2 "*** [$output] Wrong error output"
		exit 1
	}
}

test_one ' ' " "
test_one '!' "!"
test_one "$(printf '\037')" '\x1F'
test_one "$(printf '\001')" '\x01'
test_one '[' '['
test_one '\' '\\'
test_one ']' ']'
test_one '~' '~'
test_one "$(printf '\177')" '\x7F'

rm -f ? list.* main.stu || exit 2

exit 0
