#! /bin/sh

rm -f ? || exit 2

../../bin/stu.test
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo >&2 '*** (a) exit status error'
	exit 1
}

[ -e C ] && {
	echo >&2 '*** (b) C built erroneously'
	exit 1
}

../../sh/touch_old A 2 || exit 2
echo X >C || exit 2
../../sh/touch_old C 1 || exit 2

../../bin/stu.test
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo >&2 '*** (c) exit status error'
	exit 1
}

[ -e X ] || {
	echo >&2 '*** (d) X must be built'
	exit 1
}

exit 0
