#! /bin/sh

rm -f ? || exit 1

../../stu.test
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 '*** (a) exit code error'
	exit 1
}

[ -e C ] && {
	echo >&2 '*** (b) C built erroneously'
	exit 1
}

../../sh/touch_old A 2 || exit 1
echo X >C || exit 1
../../sh/touch_old C 1 || exit 1

../../stu.test
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 '*** (c) exit code error'
	exit 1
}

[ -e X ] || {
	echo >&2 '*** (d) X must be built'
	exit 1
}

exit 0
