#! /bin/sh

rm -f ?

../../stu
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 '*** (a) exit code error'
	exit 1
}

[ -e C ] && {
	echo >&2 '*** (b) C built erroneously'
	exit 1
}

echo sleep 2
sleep 2

echo 'echo X >C'
echo X >C

echo sleep 2
sleep 2

../../stu
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 '*** (c) exit code error'
	exit 1
}

[ -e X ] || {
	echo >&2 '*** (d) X must be built'
	exit 1
}

exit 0
