#! /bin/sh

rm -f ? || exit 1

../../sh/tty ../../stu.test -q -F 'A={Hello}' A >list.all
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "*** Exit code"
	exit 1
}

diff list.all stdall || {
	echo >&2 "*** Output"
	echo >&2 stdout+stderr:
	echo >&2 _____________
	cat  >&2 list.all
	echo >&2 _____________
	echo >&2 expected:
	echo >&2 _____________
	cat  >&2 stdall
	echo >&2 _____________
	exit 1
}

exit 0
