#! /bin/sh

rm -f ./@* ? || exit 2

../../bin/stu.test -c '@:[({' >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo >&2 '*** Exit status incorrect'
	rm -f ./@* ?
	exit 1
}

[ -r '@:[({' ] || {
	echo >&2 '*** Created file'
	rm -f ./@* ?
	exit 1
}

grep -Fq correct <'@:[({' || {
	echo >&2 '*** Content'
	rm -f ./@* ?
	exit 1
}

[ -r list.err ] && [ ! -s list.err ] || {
	echo >&2 '*** stderr'
	rm -f ./@* ?
	exit 1
}

rm -f ./@* ? || exit 2

exit 0
