#!/bin/sh
. ../../sh/test.sh

for j in 1 2 3 4 5 6 7 8 9 10 11 ; do
	../../sh/rm_tmps

	set +e
	../../bin/stu.test -j $j >list.out 2>list.err
	exitstatus=$?
	set -e

	[ "$exitstatus" = 0 ] || Error "exit status (j=$j)"
done
