#!/bin/sh
. ../../sh/test.sh

rm -f A

echo >&3 ../../bin/stu.test
../../bin/stu.test >list.out 2>list.err

[ -r list.out ]
[ -r list.err ]

Not grep -q -F -e 'file exists' list.out
Not grep -q -F -e 'file exists' list.err

exit 0
