#! /bin/sh

set -e

rm -f ?

#
# Build for the first time
#

../../stu.test 

[ -h W ] || {
	echo >&2 "*** 'W' must be a symbolic link"
	exit 1
}

#
# Update 'D'
#

../../sh/touch_old A
../../sh/touch_old B
../../sh/touch_old C
touch D

#
# Build for a second time
#

../../stu.test 

exit 0
