#!/bin/sh
. ../../sh/test.sh

rm -f ?
touch A

set +e
../../bin/stu.test -s >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 0 ] || Error 'exit status'
grep -q -F -e 'Nothing to be done' list.out && Error 'stdout'
[ -r list.err ] && [ ! -s list.err ] || Error 'stderr'
