#!/bin/sh
. ../../sh/test.sh

rm -f ?
touch A

set +e
../../bin/stu.test -s >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 0 ]
Not grep -q -F -e 'Nothing to be done' list.out
[ -r list.err ] ; [ ! -s list.err ]
