#! /bin/sh

#
# (1) A must be built:  B is built and thus C is built
#

../../sh/rm_tmps || exit 2

../../bin/stu.test >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo >&2 '*** Exit status (1)'
	exit 1
}

[ -r B ] || {
	echo >&2 '*** B must be built (1)'
	exit 1
}

[ -r C ] || {
	echo >&2 '*** C must be built (1)'
	exit 1
}

grep -q -F -e CORRECT A || {
	echo >&2 '*** Invalid content (1)'
	exit 1
}

#
# (2) A is already there.  Don't build B and C.
#

rm -f B C || exit 2

../../bin/stu.test >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo >&2 '*** Exit status (2)'
	exit 1
}

[ -e B ] && {
	echo >&2 '*** B must not exist (2)'
	exit 1
}

[ -e C ] && {
	echo >&2 '*** C must not exist (2)'
	exit 1
}

grep -q -F -e CORRECT A || {
	echo >&2 '*** Invalid content (2)'
	exit 1
}
