#! /bin/sh

rm -f A || exit 1

../../stu.debug >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 1 ] || {
	echo >&2 "*** Expected exit status 1, got $exitstatus"
	exit 1
}

diff list.out stdout-correct || {
	echo >&2 '*** stdout'
	exit 1
}

grep -q -E '^main\.stu:4:6: command for '"'A'"' received signal 9 \(.*ill.*\)$' list.err || {
	echo >&2 '*** stderr'
	echo >&2 '___ list.err ___'
	cat  >&2 list.err
	echo >&2 '________________'
	exit 1
}

rm -f A || exit 1

exit 0

