#!/bin/sh
. ../../sh/test.sh

Kill_Sleeps()
{
	for pid in $(ps -fA | grep 31415926535 | grep -v grep | sed -e 's/^[^[:space:]]\{1,\}[[:space:]]\{1,\}\([0-9]\{1,\}\)[[:space:]].*$/\1/') ; do
		echo >&2 "$0:  *** Killing PID '$pid'"
		kill "$pid" || true
	done

	count=$(echo $(ps -fA | grep 31415926535 | grep -v grep | wc -l))
	[ "$count" = 0 ] || {
		echo >&2 '*** Could not kill all processes'
		echo >&2 "count='$count'"
		echo >&2 'Still running:'
		ps -fA | grep 31415926535 | grep -v grep || true
		exit 1
	}
}

Kill_Sleeps

echo >&3 '../../bin/stu.test -z >list.out 2>list.err &'
../../bin/stu.test -z >list.out 2>list.err & pid=$!

# Make sure the target 'X' is finished
echo >&3 sleep 1
sleep 1

kill -TERM "$pid"

# Give Stu time to kill all processes
echo >&3 sleep 1
sleep 1

# Make sure no process is still running
if [ "$(echo $(ps -fA | grep 31415926535 | grep -v grep | wc -l))" != 0 ]; then
	echo >&3 "$0:  *** There is still a process running:"
	ps -fA | grep 31415926535 | grep -v grep >&3 || true
	exit 1
fi

# Check that statistics are not output
Not grep -q -F -e 'STATISTICS' list.out
Not grep -q -F -e 'STATISTICS' list.err

Kill_Sleeps
