#!/bin/sh
#
# Test that non-background processes don't hang.
#

. ../../sh/test.sh

#
# (1) Non-background
#

for arg in '-i' '-i -j1' ; do
	# Only '1' is written to 'X'
	echo >&3 "(1) '$arg'"
	rm -f X

	{ echo 1 ; sleep 5 ; echo 2 ; sleep 9 ; } |
		../../bin/stu.test $arg -F '@all{cat >X}' >list.out 2>list.err & pid=$!
	echo >&3 "pid='$pid'"

	sleep 1
	kill -INT "$pid"

	set +e
	wait "$pid" 2>/dev/null
	exitstatus=$?
	set -e

	[ "$exitstatus" = 130 ]
	grep -q -F -e '1' X
	Not grep -q -F -e '2' X
done

#
# (2) -j2:  background
#

for arg in '' '-j1' '-j2' ; do
	echo >&3 "(2) '$arg'"
	rm -f X || exit 1

	# This must return immediately, because stdin is set to /dev/null, and
	# nothing is written to 'X'.
	echo Bla | ../../bin/stu.test $arg -F '@all{sleep 1 ; cat >X}' >list.out 2>list.err & pid=$!
	echo >&3 "pid='$pid'"

	set +e
	wait "$pid" 2>/dev/null
	exitstatus=$?
	set -e

	# 'cat' returned without error
	[ "$exitstatus" = 0 ]
	[ -r X ] ; [ ! -s X ]
done
