#! /bin/sh

#
# Bug:  invoke the following, it leads to a failed assertion:
#
#   stu -k ahfdksaeowneowen
#
# (i.e., target not found + option -k)
#

#
# There is no stufile in this directory.
#

../../stu -k ksagiwwiuecwibve >list.out 2>list.err
exitcode="$?"

if [ "$exitcode" != 1 ] ; then
   echo >&2 "*** wrong exit code"
   exit 1
fi

if ! fgrep -q "No rule to build 'ksagiwwiuecwibve'" list.err ; then
   echo >&2 "*** missing error message"
   exit 1
fi

exit 0
