#!/bin/sh
. ../../sh/test.sh

#
# (1) When A does not exist, build it
#

echo >&3 "Case (1)"

cat >list.stu <<EOF
A = {correct}
EOF

../../bin/stu.test -f list.stu -p A >list.out 2>list.err

[ -r A ]

#
# (2) When A exists and has old timestamp, don't build it
#

echo >&3 "Case (2)"

rm -f ? list.stu

cat >list.stu <<EOF
A { exit 1 }
EOF

../../sh/touch_old A

../../bin/stu.test -f list.stu -p A >list.out 2>list.err

[ -e A ]

#
# (3) When A exists and has old timestamp and non-existing dependency, build it
#

echo >&3 "Case (3)"

rm -f ? list.stu

cat >list.stu <<EOF
A : B { cp B A }
B = {correct}
EOF

../../sh/touch_old A

../../bin/stu.test -f list.stu -p A >list.out 2>list.err

[ -r A ]
