#! /bin/sh

rm -f ? || exit 2

touch A || exit 2

../../bin/stu.test >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 0 ] || {

	echo >&2 "*** Exit status must be zero, found exitstatus=$exitstatus"

	echo >&2 _____ list.err _____
	cat  >&2 list.err
	echo >&2 ____________________

	echo >&2 _____ list.out _____
	cat  >&2 list.out
	echo >&2 ____________________

	exit 1
}

rm -f ? || exit 2

exit 0
