#! /bin/sh

rm -f ? list.* || exit 1

../../stu.test -j50 >list.out 2>list.err &
pid=$!
sleep 3 || exit 1
kill "$pid" || exit 1
wait "$!"
exitstatus=$?

[ "$exitstatus" != 0 ] || {
	echo >&2 "*** Expected an error"
	exit 1
}

grep -qF 'Removing partially built files (30)' list.err || {
	echo >&2 "*** Expecting number of removed files"
	echo >&2 '___ list.err ___'
	cat  >&2 list.err
	echo >&2 '________________'
	exit 1
}

exit 0
