#! /bin/sh

rm -f ? || exit 1

../../sh/touch_old A 1 || exit 1
touch B || exit 1

../../stu.test >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** Exit code"
	exit 1
}

grep -qxF 'Targets are up to date' list.out || {
	echo >&2 "*** Output"
	exit 1
}

[ -r list.err ] && ! [ -s list.err ] || {
	echo >&2 "*** Error output"
	exit 1
}

exit 0
