#! /bin/sh

doo() { echo "$@" ; "$@" ; }

# Make all one-character files very old
olden() {
	for file in ? ; do
		year="$(date +%Y)"
		year_old="$(expr $year - 2)"
		touch -t "$year_old"01010700 "$file"
	done
}

[ "$verbose" ] && exec 6>&2 || exec 6>/dev/null

sed -E -e '/^[[:space:]]*$/d;/^[[:space:]]*#/d' LIST.stu |
while read -r line ; do
	rm -f list.file.stu ? list.*
	echo "$line" >list.file.stu
	printf 'list.file.stu: '
	cat list.file.stu
	
	#
	# Build 
	#

	echo ../../stu.test -f list.file.stu
	../../stu.test -f list.file.stu >list.out 2>list.err
	exitcode="$?"
	echo >&6 "exitcode='$exitcode'"

	# Check exit code
	[ "$exitcode" = 0 ] || {
		echo >&2 "*** (1) Error in build"
		echo >&2 "STDOUT:"
		cat list.out
		echo >&2 _____________
		echo >&2 "STDERR:"
		cat list.err
		echo >&2 _____________
		exit 1
	}

	# Check that C was not built
	[ -e C ] && {
		echo >&2 "*** (2) 'C' must not exist"
		exit 1
	}

	#
	# Touch B - A will not be rebuilt 
	#
	doo olden
	doo touch B 
	echo ../../stu.test -f list.file.stu
	../../stu.test -f list.file.stu >list.out 2>list.err
	exitcode="$?"
	echo >&6 "exitcode='$exitcode'"

	# Check exit code
	[ "$exitcode" != 0 ] && {
		echo >&2 "*** (3) Error in rebuild"
		echo >&2 "STDOUT:"
		cat list.out
		echo >&2 _____________
		echo >&2 "STDERR:"
		cat list.err
		echo >&2 _____________
		exit 1
	}

	# Check that nothing is done
	grep -qxF 'Targets are up to date' list.out || {
		echo >&2 "*** (4) Missing 'Targets are up to date'"
		exit 1
	}

	#
	# Touch C - A will be rebuilt
	#

	doo olden
	echo 'echo X >C'
	echo X >C
	echo ../../stu.test -f list.file.stu
	../../stu.test -f list.file.stu >list.out 2>list.err
	exitcode="$?"
	echo >&6 "exitcode=«$exitcode»"

	# Check exit code
	[ "$exitcode" != 0 ] && {
		echo >&2 "*** (5) Error in rebuild"
		echo >&2 "STDOUT:"
		cat list.out
		echo >&2 _____________
		echo >&2 "STDERR:"
		cat list.err
		echo >&2 _____________
		exit 1
	}

	# Check that something is done
	grep -qFx 'Targets are up to date' list.out && {
		echo >&2 "*** (6) Erroneous 'Targets are up to date'"
		exit 1
	}

	# Check that D and E exist
	[ -r D ] && [ -r E ] || {
		echo >&2 "*** (7) Missing files 'D' or 'E'"
		exit 1
	}
	
	#
	# Touch D - A will be rebuilt
	#

	doo olden
	echo 'echo X >D'
	echo X >D
	echo ../../stu.test -f list.file.stu
	../../stu.test -f list.file.stu >list.out 2>list.err
	exitcode="$?"
	echo >&6 "exitcode=«$exitcode»"

	# Check exit code
	[ "$exitcode" != 0 ] && {
		echo >&2 "*** (8) Error in rebuild"
		echo >&2 "STDOUT:"
		cat list.out
		echo >&2 _____________
		echo >&2 "STDERR:"
		cat list.err
		echo >&2 _____________
		exit 1
	}

	# Check that something is done
	grep -qFx 'Targets are up to date' list.out && {
		echo >&2 "*** (9) Erroneous 'Targets are up to date'"
		exit 1
	}

	true
done

exitcode="$?"
echo >&6 "exitcode=«$exitcode»"

[ "$exitcode" = 0 ] &&
    rm -f list.*

exit "$exitcode"
