#! /bin/sh

rm -f ? || exit 1

../../stu.test -C '?X' >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 '*** (1) exit code'
	exit 1
}

[ \! -e X ] || {
	echo >&2 '*** (1) exists X'
	exit 1
}

grep -Fvq BUILDING_X list.out || {
	echo >&2 '*** (1) building X'
	exit 1
}

grep -Fvq BUILDING_W list.out || {
	echo >&2 '*** (2) building W'
	exit 1
}

rm -f ?

../../sh/touch_old X 1 || exit 1
touch     W || exit 1

../../stu.test -C '?X' >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 '*** (2) exit code'
	exit 1
}

[ -r X ] || {
	echo >&2 '*** (2) exists X'
	exit 1
}

grep -Fq BUILDING_X list.out || {
	echo >&2 '*** (2) building X'
	exit 1
}

grep -Fvq BUILDING_W list.out || {
	echo >&2 '*** (2) building W'
	exit 1
}

exit 0
