#! /bin/sh

rm -f ? || exit 2

../../bin/stu.test >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 0 ] || { echo >&2 "*** Exit status incorrect" ; exit 1 ; }
[ -r list.err ] && [ ! -s list.err ] || { echo >&2 "*** Standard error" ; exit 1 ; }
[ -r A ] || { echo >&2 "*** A" ; exit 1 ; }
grep -qxF correct A || { echo >&2 "*** Content" ; exit 1 ; }

../../sh/touch_old A 1 || exit 2
../../sh/touch_old C 2 || exit 2
touch B || exit 2

../../bin/stu.test >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 0 ] || { echo >&2 "*** Exit status incorrect" ; exit 1 ; }
[ -r list.err ] && [ ! -s list.err ] || { echo >&2 "*** Standard error" ; exit 1 ; }
grep -qxF 'Targets are up to date' list.out || { echo >&2 "*** Standard output" ; exit 1 ; }

exit 0
