#! /bin/sh

set -e 

rm -f ? list.*

../../bin/stu.test 

grep -qF CORRECT A || { echo >&2 "*** (1) A" ; exit 1 ; }

../../sh/touch_old A 2
touch B

../../bin/stu.test >list.out

grep -qFx 'Targets are up to date' list.out || { echo >&2 "*** (2) Stdout" ; exit 1 ; }

rm -f ? list.*
