#! /bin/sh

rm -f ? || exit 2

STU_CP=./mycp ../../bin/stu.test >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo >&2 "*** Exit status"
	exit 1
}

[ -r list.err ] && ! [ -s list.err ] || {
	echo >&2 "*** Error output"
	exit 1
}

grep -qxF MYCP list.out || {
	echo >&2 "*** MYCP"
	exit 1
}

exit 0
