#! /bin/sh

rm -f ? || exit 1

STU_CP=./mycp ../../stu.test >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** Exit code"
	exit 1
}

[ -r list.err ] && ! [ -s list.err ] || {
	echo >&2 "*** Error output"
	exit 1
}

grep -qxF MYCP list.out || {
	echo >&2 "*** MYCP"
	exit 1
}

exit 0
