#! /bin/sh

rm -Rf ? || exit 2

echo Hello >B || exit 2

../../bin/stu.test
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo >&2 "$0:  *** Exit status (1)"
	exit 1
}

../../sh/touch_old A 2 || exit 2
../../sh/touch_old list.A 2 || exit 2
echo "Hello CORRECT World" >B

../../bin/stu.test
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo >&2 "$0:  *** Exit status (2)"
	exit 1
}

grep -q -F -e CORRECT A || {
	echo >&2 "$0:  *** 'A' was not updated"
	exit 1
}

rm -Rf ? || exit 2

exit 0
