#!/bin/sh
. ../../sh/test.sh

dorm()
{
	rm -f a b a.c b.c CFLAGS LDFLAGS list.*
}

trap dorm EXIT

dorm

echo >&3 "== run A"
../../bin/stu.test

[ -r a ]
[ -r b ]

rm CFLAGS

echo >&3 "== run B"
../../bin/stu.test >list.out
echo >&3 ___
cat >&3 list.out
echo >&3 ___

echo >&3 "== grep"
! grep -q -F -e 'Compiling' list.out
grep -q -F -e 'CFLAGS' list.out
