#! /bin/sh

doo() { echo "$@" ; $@ ; }

doo rm -f ?

echo ../../stu.test
../../stu.test
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo "*** (a)"
	exit 1
}

doo rm -f B C

echo ../../stu.test
../../stu.test >list.out
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo "*** (b)"
	exit 1
}

fgrep -q 'cat D E' list.out && {
	echo "*** (c)"
	exit 1
}

exit 0
