#!/bin/sh
# TOPIC: stu -f a/
. ../../sh/test.sh

mkdir ddd.data

set +e
../../bin/stu.test -f ddd.data/ >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 1 ]
grep -q -F -e 'Option -f: "ddd.data/main.stu": ' list.err
