#! /bin/sh

doo() { echo "$@" ; $@ ; }

doo rm -f ?

doo touch A

doo sleep 2

echo ../../stu 
../../stu
exitcode="$?"
[ "$exitcode" = 0 ] || {
	echo >&2 "*** (a) exit code"
	exit 1
}

[ -e B ] || {
	echo >&2 "*** (b) 'B' was not built"
	exit 1
}

exit 0
