#! /bin/sh

rm -f ? || exit 1

../../sh/touch_old A 2

../../stu.test
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** (a) Exitcode"
	exit 1
}

[ -e B ] || {
	echo >&2 "*** (b) 'B' was not built"
	exit 1
}

exit 0
