#!/bin/sh
. ../../sh/test.sh

rm -f A B
ln -s nonexisting B

set +e
../../bin/stu.test >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 1 ] || Error 'exit status'
[ -s list.out ] && Error 'output must be empty'
grep -q -F -e "main.stu:2:5: no rule to build \"B\", needed by \"A\"" list.err ||
	Error "missing error message"
[ -e A ] && Error "'A' must not be created"

rm -f A B
