#! /bin/sh

../../bin/stu.test -V >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 0 ] || { echo >&2 '*** Exit status incorrect' ; exit 1 ; }
[ -r list.err ] && [ ! -s list.err ] || { echo >&2 '*** stderr' ; exit 1 ; }
head -1 list.out | grep -qE '^stu [0-9]' || { echo >&2 '*** stdout' ; exit 1 ; }

exit 0


