#! /bin/sh

../../sh/rm_tmps || exit 2

mkdir -p log

STU_TRACE='>' ../../bin/stu.test -F 'A={a}' >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 0 ] || exit 1
[ -e A ] || exit 1
grep -q -F -e 'stu.cc' log/trace.log
grep -q -F -e 'dep.cc' log/trace.log

../../sh/rm_tmps || exit 2

rm -fR log || exit 2

exit 0
