#! /bin/sh

[ "$EXEC_DEBUG" ] && exec 6>&2 || exec 6>/dev/null

Do()
{
	echo >&6 "$@"
	"$@"
}

Error()
{
	printf >&6 '*** %s\n' "$1"
	exit 1
}

rm -f ? list.* || Error 'rm'

echo >&6 '../../bin/stu.test >list.out 2>list.err &'
../../bin/stu.test >list.out 2>list.err &
pid=$!
echo >&6 "pid=$pid"

Do sleep 1 || Error 'sleep'

ls -l B >&6
[ -r B ] || Error 'B must exist'
pid_child=$(cat B)
echo >&6 "pid_child=$pid_child"

Do kill -s STOP $pid_child || Error 'kill -s STOP'
Do sleep 1 || Error 'sleep'
Do kill -s CONT $pid_child || Error 'kill -s CONT'

echo >&6 "wait $pid"
wait $pid
exitstatus=$?

[ "$exitstatus" = 0 ] || Error 'Exit status'
grep -q -E -e '^CORRECT$' A || Error 'Expected A to contain "CORRECT"'

exit 0
