#! /bin/sh

now=$(LC_ALL=C date)
year=$(echo $now | sed -e 's,^.* \([0-9][0-9]*\)$,\1,')
year_past=$(expr $year - 2)
date="$year_past"01010701

rm -f A B C || exit 2
touch -t "$date" B || exit 2

../../bin/stu.test 2>list.err
exitstatus=$?

[ "$exitstatus" = 1 ] || {
	echo >&2 "*** Exit status"
	echo >&2 "exitstatus=$exitstatus"
	echo >&2 'actual stderr:'
	echo >&2 __________________
	cat >&2 list.err
	echo >&2 __________________
	exit 1
}

if [ "$(grep -c -F "main.stu:11:1: timestamp of file 'B' after execution of its command is older than ../../bin/stu.test startup" list.err)" != 1 ]; then
	echo >&2 "*** Missing error message"
	echo >&2 'actual stderr:'
	echo >&2 __________________
	cat >&2 list.err
	echo >&2 __________________
	exit 1
fi

rm -f A B C || exit 2

exit 0
