#!/bin/sh
. ../../sh/test.sh

../../bin/stu.test >list.out 2>list.err & pid=$!

echo >&3 sleep 1
sleep 1

child_pid=$(sed -E -e 's,^pid=,,
t
d' list.out)
echo >&3 child_pid="$child_pid"
echo "$child_pid" | grep -q -E -x -e '[0-9]+'

kill -s STOP "$child_pid"

echo >&3 sleep 1
sleep 1

kill -s CONT "$child_pid"

echo >&3 sleep 1
sleep 1

kill -s TERM "$pid"

set +e
wait "$pid" 2>/dev/null
exitstatus=$?
set -e

[ "$exitstatus" = 143 ]
