#!/bin/sh
#
# Test the -o option.
#

. ../../sh/test.sh

#
# (1) When A does not exist, don't build it
#

echo >&3 "Case (1)"

rm -f ? main.stu

cat >main.stu <<EOF
A = {correct}
EOF

../../bin/stu.test -o A >list.out 2>list.err

[ ! -e A ] || Error '(1) A must not be built'

#
# (2) When A exists and has no dependency, do nothing
#

echo >&3 "Case (2)"

rm -f ? main.stu

cat >main.stu <<EOF
A { exit 1 }
EOF

../../sh/touch_old A

../../bin/stu.test -o A >list.out 2>list.err

[ -e A ] || Error '(2) A must not be removed'

#
# (3) When A exists and has a newer dependency, rebuild it
#

echo >&3 "Case (3)"

rm -f ? main.stu

cat >main.stu <<EOF
A : B {
   cp B A
   touch X
}
B = {correct}
EOF

../../sh/touch_old A
touch B

../../bin/stu.test -o A >list.out 2>list.err

[ -r X ] || Error '(3) X must be built'

#
# End
#

rm -f main.stu
