#! /bin/sh

set -e

rm -f ? list.*

touch A

../../bin/stu.test >list.out 2>list.err &
pid=$!

sleep 1

kill "$pid"

[ -e A ] || {
	echo >&2 "*** error (a) 'A' must be present"
	exit 1
}

rm -f ? list.*

exit 0
