#! /bin/sh
#
# Trivial dependencies.
#
# * stu 
#	* B and A are built
# * touch B
# * stu
#	* nothing is done
# 

set -e

rm -f ? 

../../stu.test >list.out 2>list.err

diff list.out stdout-1 || {
	echo >&2 '*** (1out)' 
	exit 1 
}

[ -r list.err ] && [ ! -s list.err ] || { 
	echo >&2 '*** (1err)' 
	exit 1 
}

../../sh/touch_old A 2
touch B

../../stu.test >list.out 2>list.err

diff list.out stdout-2 || {
	echo >&2 '*** (2out)' 
	exit 1 
}

[ -r list.err ] && [ ! -s list.err ] || { 
	echo >&2 '*** (2err)' 
	exit 1 
}

exit 0
