#!/bin/sh
. ../../sh/test.sh

rm -f ?

set +e
../../bin/stu.test
exitstatus=$?
set -e

[ "$exitstatus" = 0 ]

rm -f B C

set +e
../../bin/stu.test >list.out
exitstatus=$?
set -e

[ "$exitstatus" = 0 ]
Not grep -q -F -e 'cat D E' list.out

exit 0
