#! /bin/sh

rm -f ? || exit 2

echo ../../bin/stu.test A
../../bin/stu.test A || {
	echo >&2 "$0:  *** error building 'A'"
	exit 1
}

rm -f C || exit 2

echo ../../bin/stu.test A
../../bin/stu.test A || {
	echo >&2 "$0:  *** error re-building 'A'"
	exit 1
}

rm -f C || exit 2

echo ../../bin/stu.test A
if ../../bin/stu.test A | grep 'Hello >B' ; then
	echo >&2 "$0:  *** unnecessarily re-building 'B'"
	exit 1
fi

exit 0
