#! /bin/sh

#
# (1) 'A' and 'B' are both up to date; nothing to be done
#

touch A || exit 1
../../sh/touch_old B 1 || exit 1

../../stu.test -q >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** (1) Exit code"
	exit 1
}

grep -qFx 'Targets are up to date' list.out || {
	echo >&2 "*** (1) stdout"
	exit 1
}

[ -r list.err ] && [ ! -s list.err ] || {
	echo >&2 "*** (1) stderr"
	exit 1
}

#
# (2) Neither 'A' nor 'B' exist
#

rm -f A B || exit 1

../../stu.test -q >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "*** (2) Exit code"
	exit 1
}

grep -qFx 'Targets are not up to date' list.err || {
	echo >&2 "*** (2) stderr:  expected 'Targets are not up to date'"
	exit 1
}

[ -r list.out ] && [ ! -s list.out ] || {
	echo >&2 "*** (2) stdout"
	exit 1
}

#
# (3) 'A' exists, but 'B' is newer
#

../../sh/touch_old A 1 || exit 1
touch B || exit 1

../../stu.test -q >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "*** (3) Exit code"
	exit 1
}

grep -qFx 'Targets are not up to date' list.err || {
	echo >&2 "*** (3) stderr"
	exit 1
}

[ -r list.out ] && [ ! -s list.out ] || {
	echo >&2 "*** (3) stdout"
	exit 1
}

#
# (4) Only 'A' exists
#

touch A || exit 1
rm -f B || exit 1

../../stu.test -q >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "*** (4) Exit code"
	exit 1
}

grep -qFx 'Targets are not up to date' list.err || {
	echo >&2 "*** (4) stderr"
	exit 1
}

[ -r list.out ] && [ ! -s list.out ] || {
	echo >&2 "*** (4) stdout"
	exit 1
}

#
# (5) Only 'B' exists
#

rm -f A || exit 1
touch B || exit

../../stu.test -q >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "*** (5) Exit code"
	exit 1
}

grep -qFx 'Targets are not up to date' list.err || {
	echo >&2 "*** (5) stderr"
	exit 1
}

[ -r list.out ] && [ ! -s list.out ] || {
	echo >&2 "*** (5) stdout"
	exit 1
}

exit 0
