#! /bin/sh
#
# Test that when a job is executed with -i, that job stays in the
# foreground.
#

set -e
set -o pipefail

rm -f ?

echo correct | ../../bin/stu.test -i -F '>A{cat;}'

grep -qF correct A || {
	echo >&2 "*** Expected 'correct' in file 'A'"
	exit 1
}

exit 0
