#! /bin/sh

now=$(LC_ALL=C date)
year=$(echo $now | sed -e 's,^.* \([0-9][0-9]*\)$,\1,')
year_past=$(expr $year - 2)
date="$year_past"01010701

rm -f A B C

touch -t "$date" B

echo ls -l B
ls -l B

../../stu.test 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "*** Exit code"
	echo >&2 "exitcode=$exitcode"
	echo >&2 'actual stderr:'
	echo >&2 __________________
	cat >&2 list.err
	echo >&2 __________________
	exit 1
}

if [ "$(fgrep -c "main.stu:11:1: timestamp of file 'B' after execution of its command is older than ../../stu.test startup" list.err)" != 1 ]; then
	echo >&2 "*** Missing error message"
	echo >&2 'actual stderr:'
	echo >&2 __________________
	cat >&2 list.err
	echo >&2 __________________
	exit 1
fi

rm -f A B C

exit 0
