#!/bin/sh
. ../../sh/test.sh

rm -f ?

echo >&3 ../../bin/stu.test
set +e
../../bin/stu.test -k >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 1 ]
Not grep -q -F -e 'not exist' list.err

rm -f ?

echo >&3 ../../bin/stu.test -k

set +e
../../bin/stu.test -k >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 1 ]
grep -q -F -e 'CORRECT' B
grep -q -F -e "no rule to build \"nonexistingfile\"" list.err
grep -q -F -e 'targets not up to date because of errors' list.err
