#! /bin/sh

set -e

rm -f ?

#
# Build for the first time
#

../../stu.test 

[ -h W ] || {
	echo >&2 "*** 'W' is not a symbolic link"
	exit 1
}

#
# Remove 'D'
#

../../sh/touch_old A 2
../../sh/touch_old B 2
../../sh/touch_old C 2
rm D 

#
# Build for a second time
#

../../stu.test 

exit 0
