#!/bin/sh
. ../../sh/test.sh

rm -f A B

# Create B
echo $RANDOM >B
now=$(LC_ALL=C date)
year=$(echo $now | sed -e 's,^.* \([0-9][0-9]*\)$,\1,')
year_future=$(( 2 + $year ))
date="$year_future"01010700
touch -t "$date" B || exit 2

set +e
../../bin/stu.test >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 0 ] || Error 'exit status'

if cat list.out list.err | grep -q -F -i -e 'future' ; then
	Error 'error message'
fi

rm -f A B
