#! /bin/sh

rmall() {
	rm -f files list.* || exit 2
}

#
# No options
#

rmall

../../bin/stu.test >list.out 2>list.err
exitstatus=$?

if [ "$exitstatus" != 1 ]; then
	echo >&2 "*** Wrong exit status $exitstatus (A)"
	exit 1
fi

if ! fgrep -q "main.stu:29:5: command for 'list.2' failed" list.err ; then
	echo >&2 "*** Wrong error output (A)"
	exit 1
fi

if [ -r list.3 ]; then
	echo "*** File 'list.3' should not exist (A)"
	exit 1
fi

#
# -k
#

rmall

../../bin/stu.test -k >list.out 2>list.err
exitstatus=$?

if [ "$exitstatus" != 1 ]; then
	echo >&2 "*** Wrong exit status $exitstatus (B)"
	exit 1
fi

if ! grep -qF "main.stu:29:5: command for 'list.2' failed" list.err ; then
	echo >&2 "*** Wrong error output (B1)"
	exit 1
fi

if ! grep -qF "Targets not up to date because of errors" list.err ; then
	echo >&2 "*** Wrong error output (B2)"
	exit 1
fi

if [ \! -r list.3 ]; then
	echo "*** File 'list.3' should exist (B)"
	exit 1
fi

#
# -j5
#

rmall

../../bin/stu.test -j5 >list.out 2>list.err
exitstatus=$?

if [ "$exitstatus" != 1 ]; then
	echo >&2 "*** Wrong exit status $exitstatus (C)"
	exit 1
fi

if ! fgrep -q "main.stu:29:5: command for 'list.2' failed" list.err ; then
	echo >&2 "*** Wrong error output (C1)"
	exit 1
fi

if grep -qF "Targets not up to date because of errors" list.err ; then
	echo >&2 "*** Wrong error output (C2)"
	exit 1
fi

if [ \! -r list.3 ]; then
	echo "*** File 'list.3' should exist (C)"
	exit 1
fi

#
# -j5 -k
#

rmall

echo ../../bin/stu.test -j5 -k
../../bin/stu.test -j5 -k >list.out 2>list.err
exitstatus=$?

if [ "$exitstatus" != 1 ]; then
	echo >&2 "*** Wrong exit status $exitstatus (D)"
	exit 1
fi

if ! fgrep -q "main.stu:29:5: command for 'list.2' failed" list.err ; then
	echo >&2 "*** Wrong error output (D1)"
	exit 1
fi

if ! grep -qF "Targets not up to date because of errors" list.err ; then
	echo >&2 "*** Wrong error output (D2)"
	exit 1
fi

if [ \! -r list.3 ]; then
	echo "*** File 'list.3' should exist (D)"
	exit 1
fi

#
# End
#

rmall

exit 0
