#! /bin/sh

rm -f ?

STU_SHELL=./shell ../../bin/stu.test >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo >&2 '*** exitstatus incorrect'
	exit 1
}

diff list.out stdout-correct || {
	echo >&2 '*** stdout incorrect'
	echo list.out:
	echo _____
	cat list.out
	echo _____
	exit 1
}

exit 0 
