#! /bin/sh

rm -f A || exit 1

../../stu.test -- '' A >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 2 ] || {
	echo >&2 "*** Expected exit status 2, got $exitstatus"
	exit 1
}

[ -e A ] && {
	echo >&2 "*** Expected file 'A' to not exist"
	exit 1
}

rm -f A || exit 1

exit 0
