#! /bin/sh

rm -f stderr || exit 2

../../bin/stu.test -C '%version 0.9' >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 2 ] || {
	echo >&2 '*** Exit status incorrect'
	rm -f stderr
	exit 1
}

VERSION=$(cat ../../VERSION)
<stderr-in >stderr sed -e 's,\$VERSION,'"$VERSION"',g'

diff list.err stderr || {
	echo >&2 '*** stderr'

	echo >&2 "'stderr'":
	echo >&2 _____
	cat >&2 stderr
	echo >&2 _____

	echo >&2 "'list.err'":
	echo >&2 _____
	cat >&2 list.err
	echo >&2 _____

	rm -f stderr
	exit 1
}

rm -f stderr || exit 2

exit 0
