#!/bin/sh
#
# Bug:  when a symlink is created, Stu complains with "timestamp of
# target 'symlink' after execution of command is older than stu
# startup".
#
# A is the symlink that links to X.  X is a preexisting file with a
# timestamp in the past.
#

. ../../sh/test.sh

# Compute a date definitely in the past
now=$(LC_ALL=C date)
year=$(echo $now | sed -e 's/^.* \([0-9]\{1,\}\)$/\1/')
year_past=$(expr $year - 2)
date="$year_past"01010700

rm -f A X
touch -t "$date" X

../../bin/stu.test
