#!/bin/sh
#
# Test invalid first characters for environment variable names.
#

. ../../sh/test.sh

names='
1
1a
11
1aaaa
.
&
(
:
/
\
'\''
"
=
-
*
?
!
'

printf '%s' "$names" | while IFS= read -r name
do
	case "$name" in
		?*) : ;;
		*) continue ;;
	esac
	echo >&3 "name='$name'"
	../../sh/rm_tmps
	cat <<EOF >list.stu
\$($name)
EOF

	set +e
	../../bin/stu.test -f list.stu >list.out 2>list.err
	exitstatus=$?
	set -e

	echo >&3 "exitstatus=$exitstatus"
	[ "$exitstatus" = 2 ]
	grep -q -E -e 'expected name of environment variable to start with letter or underscore' list.err
done
