#! /bin/sh
#
# Trivial dependencies.
#
# * (0) stu
#	* B, D, C and A are built
# * (1) touch C
# * stu
#	* nothing is done
# * (2) touch D
# * stu
#	* nothing is done
# * (3) rm D
# * stu
#	* nothing is done
# * (4) touch B
# * stu
#	* D, C and A are rebuilt
# * (5) touch B
# * stu
#	* A is rebuilt
# 

set -e

rm -f ?

#
# (0) 
#

../../stu.test >list.out 2>list.err

diff list.out stdout-0 || { echo >&2 '*** (0out)' ; exit 1 ; }
[ -r list.err ] && [ ! -s list.err ] || { echo >&2 '*** (0err)' ; exit 1 ; }

#
# (1)
#

../../sh/touch_old D
../../sh/touch_old B
../../sh/touch_old A 
touch C

../../stu.test >list.out 2>list.err

diff list.out stdout-1 || { echo >&2 '*** (1out)' ; exit 1 ; }
[ -r list.err ] && [ ! -s list.err ] || { echo >&2 '*** (1err)' ; exit 1 ; }

#
# (2)
#

../../sh/touch_old C
../../sh/touch_old B
../../sh/touch_old A
touch D

../../stu.test >list.out 2>list.err

diff list.out stdout-2 || { echo >&2 '*** (2out)' ; exit 1 ; }
[ -r list.err ] && [ ! -s list.err ] || { echo >&2 '*** (2err)' ; exit 1 ; }

#
# (3)
#

rm D

../../stu.test >list.out 2>list.err

diff list.out stdout-3 || { echo >&2 '*** (3out)' ; exit 1 ; }
[ -r list.err ] && [ ! -s list.err ] || { echo >&2 '*** (3err)' ; exit 1 ; }

#
# (4)
#

../../sh/touch_old C
../../sh/touch_old A
touch B

../../stu.test >list.out 2>list.err

diff list.out stdout-4 || { echo >&2 '*** (4out)' ; exit 1 ; }
[ -r list.err ] && [ ! -s list.err ] || { echo >&2 '*** (4err)' ; exit 1 ; }

#
# (5)
#

../../sh/touch_old D
../../sh/touch_old C
../../sh/touch_old A
touch B

../../stu.test >list.out 2>list.err

diff list.out stdout-5 || { echo >&2 '*** (5out)' ; exit 1 ; }
[ -r list.err ] && [ ! -s list.err ] || { echo >&2 '*** (5err)' ; exit 1 ; }

exit 0
