#! /bin/sh

export TERM=xterm

echo '(a)'

../../sh/rm_tmps || exit 2

LD_PRELOAD=../../bin/preload-tty.so STU_PRELOAD_TTY=o ../../bin/stu.test -F 'A: B {exit 1;} B={1}' >list.out 2>list.err
exitstatus=$?

echo "list.out:"
echo ____
cat  list.out
echo ____
echo "list.err:"
echo ____
cat  list.err
echo ____

[ "$exitstatus" = 1 ] || { echo >&2 "*** (a) Expected exit status 1, not $exitstatus" ; exit 1 ; }
grep -q -F -e '' list.out && { echo >&2 "*** (a) list.out must not contain color" ; exit 1 ; }
grep -q -F -e '' list.err || { echo >&2 "*** (a) list.err must contain color" ;     exit 1 ; }

echo '(b)'

../../sh/rm_tmps || exit 2

LD_PRELOAD=../../bin/preload-tty.so STU_PRELOAD_TTY=e ../../bin/stu.test -F 'A: B {exit 1;} B={1}' >list.out 2>list.err
exitstatus=$?

echo "list.out:"
echo ____
cat  list.out
echo ____
echo "list.err:"
echo ____
cat  list.err
echo ____

[ "$exitstatus" = 1 ] || { echo >&2 "*** (b) Expected exit status 1, not $exitstatus" ; exit 1 ; }
grep -q -F -e '' list.out || { echo >&2 "*** (b) list.err must contain color" ;     exit 1 ; }
grep -q -F -e '' list.err && { echo >&2 "*** (a) list.out must not contain color" ; exit 1 ; }

exit 0
