#! /bin/sh
#
# A dependency of ./X does not match a rule target of C/X, where C is the actual name of the current
# directory. 
#

set -e

rm -f ? list.* 

dir=$(pwd)

cat >list.stu <<EOF
A:  ./B    { touch A ; }
'$dir'/B:  { touch '$dir'/B ; touch A ; }
EOF

set +e
../../bin/stu.test -f list.stu >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 1 ] || {
	echo >&2 '*** Expected exit status 1'
	exit 1
}

grep -qF "list.stu:1:5: no rule to build \"./B\", needed by \"A\"" list.err || {
	echo >&2 '*** Expect error message'
	exit 1
}

rm -f ? list.* 

exit 0
