#! /bin/sh

now=$(LC_ALL=C date)
year=$(echo $now | sed -e 's,^.* \([0-9][0-9]*\)$,\1,')
year_a=$(expr $year - 3)
year_b=$(expr $year - 2)
date_a="$year_a"01010700
date_b="$year_b"01010700

rm -f A B || exit 1

touch -t "$date_a" A || exit 1
touch -t "$date_b" B || exit 1

../../stu.test 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** Wrong exit code:  $exitcode"
	exit 1
}

grep -qF "warning: File target 'A' which has no command is older than its dependency" list.err || {
	echo >&2 "*** Warning is missing"
	exit 1
}

rm -f A B || exit 1

exit 0

