#!/bin/sh
. ../../sh/test.sh

rm -f ?

echo CORRECT1 >B

set +e
../../bin/stu.test >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 0 ] || Error 'exit status'

diff A content-correct || Error 'content'
