#! /bin/sh

STU_OPTIONS=X ../../bin/stu.test >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 4 ] || {
	echo >&2 "*** Expected exit status 4, not $exitstatus"
	exit 1
}

grep -q -F -e 'invalid option -X' list.err || {
	echo >&2 '*** Invalid stderr'
	exit 1
}

exit 0
