#! /bin/sh
#
# Empty argument to -c
#

rm -f ? || exit 2

../../bin/stu.test -c '' >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 4 ] || {
	echo >&2 '*** Exit status incorrect'
	exit 1
}

diff list.err stderr-correct || {
	echo >&2 '*** stderr'
	echo >&2 list.err:
	echo >&2 ______
	cat >&2 list.err
	echo >&2 ______
	exit 1
}

exit 0
