#! /bin/sh

set -e

rm -f -- ? '[?!@A]' ']A@!?['

../../stu.test -J -a -- '[?!@A]' ']A@!?['

[ -r '[?!@A]' ] || { echo >&2 "*** First file" ; exit 1 ; }
[ -r ']A@!?[' ] || { echo >&2 "*** Second file" ; exit 1 ; }

rm -f -- ? '[?!@A]' ']A@!?['

exit 0

