#! /bin/sh

doo() { echo "$@" ; "$@" ; }

doo rm -Rf data-X-dir

echo >&2 ../../stu.test 
../../stu.test 
if [ "$?" != 0 ]; then
	echo "$0:  *** first stu failed"
	exit 1
fi

echo >&2 touch data-X-dir/unrelatedfile
touch data-X-dir/unrelatedfile || {
	exit 1
}

echo >&2 ../../stu.test
../../stu.test >list.output
if [ "$?" != 0 ]; then
	exit 1
fi

grep -Fq 'Nothing to be done' list.output || {
	echo >&2 "$0:  *** stu did not output 'Nothing to be done'"
	exit 1
}

doo rm -Rf data-X-dir list.output A list.*

exit 0
