#! /bin/sh

set -e

rm -f X Y Z

../../stu.test -j2 >list.out 2>list.err &
pid="$!"

sleep 2

if [ "$(echo $(ps -fA | grep 2837415 | grep -v grep | wc -l))" = 0 ]; then
	echo >&2 "$0:  *** Stu is not running"
	exit 1
fi

kill -TERM $pid 

sleep 1

if [ "$(echo $(ps -fA | grep 2837415 | grep -v grep | wc -l))" != 0 ]; then
	echo >&2 "$0:  *** Sleep is still running"
	ps -fA | grep 2837415
	exit 1
fi

rm -f ?

exit 0
