#! /bin/sh

rm -f ?

../../stu.test -ds >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || { 
	echo >&2 '*** Exit code' ; exit 1 ; 
}

[ -r list.out ] && [ ! -s list.out ] || { echo >&2 '*** Stdout not empty' ; exit 1 ; }
[ -r list.err ] && [ -s list.err ] || { echo >&2 '*** Stderr empty' ; exit 1 ; }

lines="$(echo $(<list.err wc -l))"
[ "$lines" -gt 10 ] || { echo >&2 '*** Not enough error output' ; exit 1 ; }
grep -Eqv '^DEBUG  ' list.err && { echo >&2 '*** Invalid error output' ; exit 1 ; }

exit 0

