#!/bin/sh
#
# Trivial dependencies.
#
# * (0) stu
#	* B and A are built
# * (1) touch C
# * stu
#	* nothing is done
# * (2) touch D
# * stu
#	* nothing is done
# * (3) rm D
# * stu
#	* nothing is done
# * (4) touch B
# * stu
#	* D, C and A are rebuilt
# * (5) touch B
# * stu
#	* A is rebuilt
#

. ../../sh/test.sh

rm -f ?

#
# (0)
#

../../bin/stu.test >list.out 2>list.err

diff list.out stdout-0 || Error '(0) stdout'
[ -r list.err ] && [ ! -s list.err ] || Error '(0) stderr'
[ -r A ] || Error '(0) A'
[ -r B ] || Error '(0) B'

#
# (1)
#

../../sh/touch_old A 2
../../sh/touch_old B 2
touch C

../../bin/stu.test >list.out 2>list.err

diff list.out stdout-1 || Error '(1) stdout'
[ -r list.err ] && [ ! -s list.err ] || Error '(1) stderr'

#
# (2)
#

../../sh/touch_old A 2
../../sh/touch_old B 2
../../sh/touch_old C 2
touch D

../../bin/stu.test >list.out 2>list.err

diff list.out stdout-2 || Error '(2) stdout'
[ -r list.err ] && [ ! -s list.err ] || Error '(2) stderr'

#
# (3)
#

../../sh/touch_old A 2
../../sh/touch_old B 2
../../sh/touch_old C 2
rm D

../../bin/stu.test >list.out 2>list.err

diff list.out stdout-3 || Error '(3) stdout'
[ -r list.err ] && [ ! -s list.err ] || Error '(3) stderr'

#
# (4)
#

../../sh/touch_old A 2
../../sh/touch_old C 2
touch B

../../bin/stu.test >list.out 2>list.err

diff list.out stdout-4 || Error '(4) stdout'
[ -r list.err ] && [ ! -s list.err ] || Error '(4) stderr'
[ -r D ] || Error '(4) D'

#
# (5)
#

../../sh/touch_old A 2
../../sh/touch_old C 2
../../sh/touch_old D 2
touch B

../../bin/stu.test >list.out 2>list.err

diff list.out stdout-5 || Error '(5) stdout'
[ -r list.err ] && [ ! -s list.err ] || Error '(5) stderr'
