#!/bin/sh
. ../../sh/test.sh

../../bin/stu.test -j2 -F '@all: A B; $X{sleep 10;}' >list.out 2>list.err & pid=$!

sleep 1
kill -s INT "$pid"

set +e
wait "$pid"
exitstatus=$?
set -e

[ "$exitstatus" = 130 ]
Not grep -q -F -i -e 'terminating all jobs' list.out
grep -q -F -i -e 'terminating all jobs' list.err
