#! /bin/sh

rm -f ?

echo ../../stu -k 
../../stu -k 2>list.err
exitcode="$?"
if [ "$exitcode" != 2 ] ; then
	echo >& '*** error (A)'
	exit 1
fi

[ -r B ] || {
	echo >&2 '*** error (B)'
	exit 1
}

cmp list.err stderr || {
	echo >&2 '*** error (C)'
	echo >&2 stderr:
	echo >&2 _______________
	cat >&2 list.err
	echo >&2 _______________
	exit 1
}
