#! /bin/sh

N=999

rm -f ? list.* || exit 2

echo "../../bin/stu.test -j$N &"
../../bin/stu.test -j$N >list.out 2>list.err &
pid=$!

begin=$(../../sh/now)

# Write until a first line has been written
while [ \! -s list.out ] ; do
	now=$(../../sh/now)
	if [ "$now" -gt "$((begin + 2))" ] ; then
		echo >&2 '*** No output written in first 2 seconds'
		break
	fi
done

echo "kill -s TERM $pid"
kill -s TERM "$pid" || {
	echo >&2 '*** Kill'
	exit 1
}

echo sleep 1
sleep 1 || exit 2

if [ "$(echo $(ps -fA | grep 74634275 | grep -v grep | wc -l))" \!= 0 ]; then
	echo >&2 "$0: *** Stu is still running"
	exit 1
fi

exit 0
