#!/bin/sh
. ../../sh/test.sh

set +e
../../bin/stu.test --question -F 'A={x}' A >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 1 ]
grep -q -E -e 'Targets are not up to date' list.err
[ -e list.out -a \! -s list.out ]
