#! /bin/sh

set -e 

doo() { echo >&2 "$@" ; "$@" ; }

doo rm -f ? list.*

doo ../../stu.test 

grep -qF CORRECT A

doo sleep 2
doo touch B

doo ../../stu.test >list.out

grep -qF 'Nothing to be done' list.out

doo rm -f ? list.*
