#!/bin/sh
. ../../sh/test.sh

#
# (1) File does not exist
#

rm -f A

set +e
../../bin/stu.test -F 'A;' >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 1 ] || Error '(1) exit status'
grep -q -F -e "expected the file without command and without dependencies \"A\" to exist" list.err || Error '(1) stderr A'
grep -q -F -e 'Option -F:' list.err || Error '(1) stderr B'
[ -r list.out ] && [ ! -s list.out ] || Error '(1) stdout'

#
# (2) File exists
#

touch A

set +e
../../bin/stu.test -F 'A;' >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 0 ] || Error '(2) exit status'
grep -q -F -x -e 'Targets are up to date' list.out || Error '(2) stdout'
[ -r list.err ] && [ \! -s list.err ] || Error '(2) stderr'
