#!/bin/sh
. ../../sh/test.sh

#
# (1) File does not exist
#

rm -f A

set +e
../../bin/stu.test -F 'A;' >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 1 ]
grep -q -F -e "expected the file without command and without dependencies \"A\" to exist" list.err
grep -q -F -e 'Option -F:' list.err
[ -r list.out ] && [ ! -s list.out ]

#
# (2) File exists
#

touch A

set +e
../../bin/stu.test -F 'A;' >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 0 ]
grep -q -F -x -e 'Targets are up to date' list.out
[ -r list.err ] ; [ ! -s list.err ]
