#! /bin/sh

../../stu -f - >list.out 2>list.err <<EOF 
A: B { cp B A }
>B { echo correct }
EOF
exitcode="$?"

[ "$exitcode" = 0 ] || { echo >&2 '*** Exit code' ; exit 1 ; }
[ -r list.err -a \! -s list.err ] || { echo >&2 '*** stderr' ; exit 1 ; }
grep -qE '^correct$' A || { echo '*** Content' ; exit 1 ; }

exit 0
