#! /bin/sh
#
# Test that '-f -' makes Stu read standard input as an input file. 
#

../../stu.test -f - >list.out 2>list.err <<EOF 
A: B { cp B A }
>B { echo correct }
EOF
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** Expected exit code 0, not '$exitcode'" 
	exit 1
}

[ -r list.err ] && [ ! -s list.err ] || { echo >&2 '*** stderr' ; exit 1 ; }

grep -qE '^correct$' A || { echo '*** Content' ; exit 1 ; }

exit 0
