#!/bin/sh
. ../../sh/test.sh

Do()
{
	echo >&3 "$@"
	"$@"
}

../../bin/stu.test >list.out 2>list.err & pid=$!
echo >&3 "pid=$pid"

Do sleep 1

ls -l B >&3
[ -r B ]
pid_child=$(cat B)
echo >&3 "pid_child=$pid_child"

Do kill -s STOP $pid_child
Do sleep 1
Do kill -s CONT $pid_child

echo >&3 "wait $pid"
set +e
wait $pid
exitstatus=$?
set -e

[ "$exitstatus" = 0 ]
grep -q -F -x -e 'CORRECT' A
