#!/bin/sh
. ../../sh/test.sh

rm -f ? list.*

set +e
../../bin/stu.test -k >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 2 ] || Error 'exit status'
cmp -s list.out stdout-correct || Error 'stdout'
cmp -s list.err stderr-correct || Error 'stderr'
[ -r Y ] || Error 'Y'

rm -f ? list.*
