#! /bin/sh

rm -Rf ? || exit 1

echo Hello >B || exit 1

../../stu.test
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "$0:  *** Exitcode (1)"
	exit 1
}

../../sh/touch_old A 2 || exit 1
../../sh/touch_old list.A 2 || exit 1
echo "Hello CORRECT World" >B

../../stu.test
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "$0:  *** Exitcode (2)"
	exit 1
}

grep -qF CORRECT A || {
	echo >&2 "$0:  *** 'A' was not updated"
	exit 1
}

rm -Rf ? || exit 1

exit 0
