#! /bin/sh

#
# (1) All files exist
#

touch P || exit 2
touch Q || exit 2
touch R || exit 2

../../bin/stu.test -q P Q R >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo >&2 "*** (1) Exit status"
	exit 1
}

grep -qFx 'Targets are up to date' list.out || {
	echo >&2 "*** (1) stdout"
	exit 1
}

[ -r list.err ] && [ ! -s list.err ] || {
	echo >&2 "*** (1) stderr"
	exit 1
}

#
# (2) No file exists
#

rm -f P Q R || exit 2

../../bin/stu.test -q >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 1 ] || {
	echo >&2 "*** (2) Exit status"
	exit 1
}

grep -qFx 'Targets are not up to date' list.err || {
	echo >&2 "*** (2) stderr:  expected 'Targets are not up to date'"
	exit 1
}

[ -r list.out ] && [ ! -s list.out ] || {
	echo >&2 "*** (2) stdout"
	exit 1
}

#
# (3) Only P exists
#

rm -f Q R || exit 2
touch P || exit 2

../../bin/stu.test -q >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 1 ] || {
	echo >&2 "*** (3) Exit status"
	exit 1
}

grep -qFx 'Targets are not up to date' list.err || {
	echo >&2 "*** (3) stderr"
	exit 1
}

[ -r list.out ] && [ ! -s list.out ] || {
	echo >&2 "*** (3) stdout"
	exit 1
}

#
# (4) Only Q exists
#

rm -f P R || exit 2
touch Q || exit 2

../../bin/stu.test -q >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 1 ] || {
	echo >&2 "*** (4) Exit status"
	exit 1
}

grep -qFx 'Targets are not up to date' list.err || {
	echo >&2 "*** (4) stderr"
	exit 1
}

[ -r list.out ] && [ ! -s list.out ] || {
	echo >&2 "*** (4) stdout"
	exit 1
}

#
# (5) Only R exists
#

rm -f P Q || exit 2
touch R || exit 2

../../bin/stu.test -q >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 1 ] || {
	echo >&2 "*** (5) Exit status"
	exit 1
}

grep -qFx 'Targets are not up to date' list.err || {
	echo >&2 "*** (5) stderr"
	exit 1
}

[ -r list.out ] && [ ! -s list.out ] || {
	echo >&2 "*** (5) stdout"
	exit 1
}

#
# (6) Only P and Q exist
#

rm -f R || exit 2
touch P || exit 2
touch Q || exit 2

../../bin/stu.test -q >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 1 ] || {
	echo >&2 "*** (6) Exit status"
	exit 1
}

grep -qFx 'Targets are not up to date' list.err || {
	echo >&2 "*** (6) stderr"
	exit 1
}

[ -r list.out ] && [ ! -s list.out ] || {
	echo >&2 "*** (6) stdout"
	exit 1
}

#
# (7) Only P and R exist
#

rm -f Q || exit 2
touch P || exit 2
touch R || exit 2

../../bin/stu.test -q >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 1 ] || {
	echo >&2 "*** (7) Exit status"
	exit 1
}

grep -qFx 'Targets are not up to date' list.err || {
	echo >&2 "*** (7) stderr"
	exit 1
}

[ -r list.out ] && [ ! -s list.out ] || {
	echo >&2 "*** (7) stdout"
	exit 1
}

#
# (8) Only Q and R exist
#

rm -f P || exit 2
touch Q || exit 2
touch R || exit 2 

../../bin/stu.test -q >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 1 ] || {
	echo >&2 "*** (8) Exit status"
	exit 1
}

grep -qFx 'Targets are not up to date' list.err || {
	echo >&2 "*** (8) stderr"
	exit 1
}

[ -r list.out ] && [ ! -s list.out ] || {
	echo >&2 "*** (8) stdout"
	exit 1
}

exit 0
