#! /bin/sh

#
# (1) All files exist
#

touch P || exit 1
touch Q || exit 1
touch R || exit 1

../../stu.test -q P Q R >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** (1) Exit code"
	exit 1
}

grep -qFx 'Targets are up to date' list.out || {
	echo >&2 "*** (1) stdout"
	exit 1
}

[ -r list.err ] && [ ! -s list.err ] || {
	echo >&2 "*** (1) stderr"
	exit 1
}

#
# (2) No file exists
#

rm -f P Q R || exit 1

../../stu.test -q >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "*** (2) Exit code"
	exit 1
}

grep -qFx 'Targets are not up to date' list.err || {
	echo >&2 "*** (2) stderr:  expected 'Targets are not up to date'"
	exit 1
}

[ -r list.out ] && [ ! -s list.out ] || {
	echo >&2 "*** (2) stdout"
	exit 1
}

#
# (3) Only P exists
#

rm -f Q R || exit 1
touch P || exit 1

../../stu.test -q >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "*** (3) Exit code"
	exit 1
}

grep -qFx 'Targets are not up to date' list.err || {
	echo >&2 "*** (3) stderr"
	exit 1
}

[ -r list.out ] && [ ! -s list.out ] || {
	echo >&2 "*** (3) stdout"
	exit 1
}

#
# (4) Only Q exists
#

rm -f P R || exit 1
touch Q || exit 1

../../stu.test -q >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "*** (4) Exit code"
	exit 1
}

grep -qFx 'Targets are not up to date' list.err || {
	echo >&2 "*** (4) stderr"
	exit 1
}

[ -r list.out ] && [ ! -s list.out ] || {
	echo >&2 "*** (4) stdout"
	exit 1
}

#
# (5) Only R exists
#

rm -f P Q || exit 1
touch R || exit 1

../../stu.test -q >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "*** (5) Exit code"
	exit 1
}

grep -qFx 'Targets are not up to date' list.err || {
	echo >&2 "*** (5) stderr"
	exit 1
}

[ -r list.out ] && [ ! -s list.out ] || {
	echo >&2 "*** (5) stdout"
	exit 1
}

#
# (6) Only P and Q exist
#

rm -f R || exit 1
touch P || exit 1
touch Q || exit 1

../../stu.test -q >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "*** (6) Exit code"
	exit 1
}

grep -qFx 'Targets are not up to date' list.err || {
	echo >&2 "*** (6) stderr"
	exit 1
}

[ -r list.out ] && [ ! -s list.out ] || {
	echo >&2 "*** (6) stdout"
	exit 1
}

#
# (7) Only P and R exist
#

rm -f Q || exit 1
touch P || exit 1
touch R || exit 1

../../stu.test -q >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "*** (7) Exit code"
	exit 1
}

grep -qFx 'Targets are not up to date' list.err || {
	echo >&2 "*** (7) stderr"
	exit 1
}

[ -r list.out ] && [ ! -s list.out ] || {
	echo >&2 "*** (7) stdout"
	exit 1
}

#
# (8) Only Q and R exist
#

rm -f P || exit 1
touch Q || exit 1
touch R || exit 1 

../../stu.test -q >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "*** (8) Exit code"
	exit 1
}

grep -qFx 'Targets are not up to date' list.err || {
	echo >&2 "*** (8) stderr"
	exit 1
}

[ -r list.out ] && [ ! -s list.out ] || {
	echo >&2 "*** (8) stdout"
	exit 1
}

exit 0
