#! /bin/sh

#
# (1) All files exist
#

touch P
touch Q 
touch R

../../stu.test -q P Q R >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** (1) Exit code"
	exit 1
}

grep -qF 'Nothing to be done' list.out || {
	echo >&2 "*** (1) stdout"
	exit 1
}

[ -r list.err -a \! -s list.err ] || {
	echo >&2 "*** (1) stderr"
	exit 1
}

#
# (2) No file exists
#

rm -f P Q R

../../stu.test -q >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "*** (2) Exit code"
	exit 1
}

grep -qF 'Targets are not up to date' list.out || {
	echo >&2 "*** (2) stdout"
	exit 1
}

[ -r list.err -a \! -s list.err ] || {
	echo >&2 "*** (2) stderr"
	exit 1
}

#
# (3) Only P exists
#

rm -f Q R
touch P

../../stu.test -q >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "*** (3) Exit code"
	exit 1
}

grep -qF 'Targets are not up to date' list.out || {
	echo >&2 "*** (3) stdout"
	exit 1
}

[ -r list.err -a \! -s list.err ] || {
	echo >&2 "*** (3) stderr"
	exit 1
}

#
# (4) Only Q exists
#

rm -f P R
touch Q

../../stu.test -q >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "*** (4) Exit code"
	exit 1
}

grep -qF 'Targets are not up to date' list.out || {
	echo >&2 "*** (4) stdout"
	exit 1
}

[ -r list.err -a \! -s list.err ] || {
	echo >&2 "*** (4) stderr"
	exit 1
}

#
# (5) Only R exists
#

rm -f P Q
touch R

../../stu.test -q >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "*** (5) Exit code"
	exit 1
}

grep -qF 'Targets are not up to date' list.out || {
	echo >&2 "*** (5) stdout"
	exit 1
}

[ -r list.err -a \! -s list.err ] || {
	echo >&2 "*** (5) stderr"
	exit 1
}

#
# (6) Only P and Q exist
#

rm -f R
touch P
touch Q

../../stu.test -q >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "*** (6) Exit code"
	exit 1
}

grep -qF 'Targets are not up to date' list.out || {
	echo >&2 "*** (6) stdout"
	exit 1
}

[ -r list.err -a \! -s list.err ] || {
	echo >&2 "*** (6) stderr"
	exit 1
}

#
# (7) Only P and R exist
#

rm -f Q
touch P
touch R

../../stu.test -q >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "*** (7) Exit code"
	exit 1
}

grep -qF 'Targets are not up to date' list.out || {
	echo >&2 "*** (7) stdout"
	exit 1
}

[ -r list.err -a \! -s list.err ] || {
	echo >&2 "*** (7) stderr"
	exit 1
}

#
# (8) Only Q and R exist
#

rm -f P
touch Q
touch R

../../stu.test -q >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "*** (8) Exit code"
	exit 1
}

grep -qF 'Targets are not up to date' list.out || {
	echo >&2 "*** (8) stdout"
	exit 1
}

[ -r list.err -a \! -s list.err ] || {
	echo >&2 "*** (8) stderr"
	exit 1
}

exit 0
