#! /bin/sh

export STU_OPTIONS=-Ey

../../bin/stu.test >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 2 ] || {
	echo >&2 "*** Expected exit status 2, not $exitstatus"
	exit 1
}

grep -qF 'Explanation: Each Stu script can declare a version to which it is compatible' list.err || {
	echo >&2 "*** Expected a message"
	exit 1
}

exit 0
