#! /bin/sh

set -o pipefail

now=$(LC_ALL=C date)
year=$(echo $now | sed -e 's,^.* \([0-9][0-9]*\)$,\1,')
year_a=$(expr $year - 3)
year_b=$(expr $year - 2)
date_a="$year_a"01010700
date_b="$year_b"01010700

rm -f A B || exit 2
touch -t "$date_a" A || exit 2
touch -t "$date_b" B || exit 2

../../bin/stu.test 2>list.err
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo >&2 "*** Exit status incorrect:  $exitstatus"
	exit 1
}

grep -qF "warning: file target \"A\" which has no command is older than its dependency" list.err || {
	echo >&2 "*** Warning is missing"
	exit 1
}

rm -f A B || exit 2

exit 0
