#! /bin/sh

doo() { echo "$@" ; "$@" ; }

#
# Without -k
#

doo rm -f ? ?? 

../../stu.test >list.out 2>list.err
exitcode="$?"

if [ "$exitcode" != "2" ]; then
    echo >&2 "*** wrong exit code (run A)"
    exit 1
fi

if ! grep -qF "B1:1:4: expected a dependency" list.err ; then
    echo >&2 "*** not containing 'invalid token' in error output"
    exit 1
fi

if grep -qF "Targets not up to date because of errors" list.err ; then
    echo >&2 "*** containing '*** Targets not up to date because of errors' in error output"
    exit 1
fi

#
# With -k
#

doo rm -f ? ?? 

../../stu.test -k >list.out 2>list.err
exitcode="$?"

if [ "$exitcode" != "2" ]; then
    echo >&2 "*** wrong exit code (run A)"
    exit 1
fi

if ! grep -qF "B1:1:4: expected a dependency" list.err ; then
    echo >&2 "*** not containing 'invalid token' in error output"
    exit 1
fi

if ! grep -qF "Targets not up to date because of errors" list.err ; then
    echo >&2 "*** not containing '*** Targets not up to date because of errors' in error output"
    exit 1
fi

#
# End
#

rm -f ? ?? 

exit 0
