#! /bin/sh

doo() { echo "$@" ; "$@" ; }

#
# (1) No options
#

echo >&2 RUN '(1)'

doo rm -f ?

../../stu.test >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "$: *** Variant without options failed (1)"
	exit 1
}

#
# (2) With -k 
#

echo >&2 RUN '(2)'

doo rm -f ?
 
../../stu.test -k >list.out 2>list.err &
pid="$!"

doo sleep 2

if [ $(ps -fe | grep 74634275 | grep -v grep | wc -l) = 0 ]; then
	echo >&2 "$0: *** Stu is not running (2a)"
	exit 1
fi

echo "kill -TERM $pid"
kill -TERM "$pid"  || {
	echo >&2 "$0: *** Kill (2)"
	exit 1
}

doo sleep 1

if [ $(ps -fe | grep 74634275 | grep -v grep | wc -l) != 0 ]; then
	echo >&2 "$0: *** Stu is still running (2b)"
	ps -fe | grep 74634275 | grep -v grep
	echo _______________
	exit 1
fi

wait "$pid"
exitcode="$?"

echo "exitcode='$exitcode'"

#
# (3) With -j2
#

echo >&2 RUN '(3)'

doo rm -f ?

../../stu.test -j2 >list.out 2>list.err
exitcode="$?"

if [ "$exitcode" != 1 ]; then
	echo >&2 "$: *** Variant without options failed (3)"
	exit 1
fi

#
# (4) With -j2 -k 
#

echo >&2 RUN '(4)'

doo rm -f ?
 
../../stu.test -j2 -k >list.out 2>list.err &
pid="$!"

doo sleep 2

if [ $(ps -fe | grep 74634275 | grep -v grep | wc -l) = 0 ]; then
	echo >&2 "*** Stu is not running (4a)"
	exit 1
fi

echo "kill -TERM $pid"
kill -TERM "$pid" || {
	echo >&2 '*** Kill (4)'
	exit 1
}

sleep 1

if [ $(ps -fe | grep 74634275 | grep -v grep | wc -l) != 0 ]; then
	echo >&2 "$0: *** Stu is still running (4b)"
	exit 1
fi

#
# End
#

exit 0
