#! /bin/sh

#
# (1) No options
#

echo >&2 RUN '(1)'

rm -f ? || exit 1

../../stu.test >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 "$: *** Variant without options failed (1)"
	exit 1
}

#
# (2) With -k 
#

echo >&2 RUN '(2)'

rm -f ? || exit 1
 
if [ "$(echo $(ps -fA | grep 74634275 | grep -v grep | wc -l))" != 0 ]; then
	echo >&2 "$0: *** There are still processes running from previously (2b)"
	exit 1
fi

../../stu.test -k >list.out 2>list.err &
pid="$!"

sleep 2 || exit 1

if [ "$(echo $(ps -fA | grep 74634275 | grep -v grep | wc -l))" = 0 ]; then
	echo >&2 "$0: *** Stu is not running (2a)"
	exit 1
fi

ps -fA | grep "$pid"
kill -TERM "$pid"  || {
	echo >&2 "$0: *** Kill (2)"
	exit 1
}

sleep 1 || exit 1

ps -fA | grep  74634275
ps -fA | grep  stu

if [ "$(echo $(ps -fA | grep 74634275 | grep -v grep | wc -l))" != 0 ]; then
	echo >&2 "$0: *** Stu is still running (2b)"
	ps -fA | grep 74634275 | grep -v grep
	echo _______________
	exit 1
fi

wait "$pid"
exitcode="$?"

#
# (3) With -j2
#

echo >&2 RUN '(3)'

rm -f ? || exit 1

../../stu.test -j2 >list.out 2>list.err
exitcode="$?"

if [ "$exitcode" != 1 ]; then
	echo >&2 "$: *** Variant without options failed (3)"
	exit 1
fi

#
# (4) With -j2 -k 
#

echo >&2 RUN '(4)'

rm -f ? || exit 1
 
../../stu.test -j2 -k >list.out 2>list.err &
pid="$!"

sleep 2 || exit 1

if [ "$(echo $(ps -fA | grep 74634275 | grep -v grep | wc -l))" = 0 ]; then
	echo >&2 "*** Stu is not running (4a)"
	exit 1
fi

kill -TERM "$pid" || {
	echo >&2 '*** Kill (4)'
	exit 1
}

sleep 1 || exit 1

if [ "$(echo $(ps -fA | grep 74634275 | grep -v grep | wc -l))" != 0 ]; then
	echo >&2 "$0: *** Stu is still running (4b)"
	exit 1
fi

#
# End
#

exit 0
