#! /bin/sh

preload_tty_so=$(cd ../.. ; pwd)/bin/preload-tty.so
CMDPREFIX_TTY="TERM=xterm"
LD_PRELOAD_VALUE_TTY="$preload_tty_so"

( cd ../.. ; sh/ccpreload src/preload-tty.cc bin/preload-tty.so ; ) || exit 2

rm -f ? || exit 2

eval $CMDPREFIX_TTY LD_PRELOAD=$LD_PRELOAD_VALUE_TTY ../../bin/stu.test \
	-F "'A=B;B={Hello}'" || {
	echo >&2 "*** (a)"
	exit 1
}

eval $CMDPREFIX_TTY LD_PRELOAD=$LD_PRELOAD_VALUE_TTY ../../bin/stu.test \
	-F "'A=B;B={Hello}'" \>list.all 2\>\&1 || {
	echo >&2 "*** (b)"
	exit 1
}

if ! cmp -s list.all stdall ; then
	echo >&2 "*** (c)"
	diff >&2 list.all stdall
	exit 1
fi

exit 0
