#! /bin/sh

set -e

rm -f ? list.*

# * 'B' is a symlink to an existing file
ln -s W B
echo aaa >W

# * stu is called: 'A' is built

../../stu.test >list.out 2>list.err

[ -r A ] || { echo >&2 "*** 'A' must exist (1)" ; exit 1 ; }
grep -qF aaa A || { echo >&2 "*** invalid content in 'A' (1)" ; exit 1 ; }

# * the file pointed to by 'B' is updated
../../sh/touch_old A
../../sh/touch_old B
echo bbb >W

# * stu is called: 'A' should be rebuilt 
../../stu.test >list.out 2>list.err

grep -qF bbb A || { echo >&2 "*** invalid content in 'A' (2)" ; exit 1 ; }
set +e
grep -qF 'Nothing to be done' list.out 
exitcode="$?"
[ "$exitcode" = 1 ] || {
	echo >&2 "*** Stu must do something (2)"
	exit 1
}

rm -f ? list.* || exit 1

exit 0
