#!/bin/sh
. ../../sh/test.sh
MAGIC_NUMBER=986745321

kill_sleeps()
{
	echo >&3 "kill_sleeps()"
	for pid in $(ps -fA | grep $MAGIC_NUMBER | grep -v grep | sed -e 's/^[^[:space:]]\{1,\}[[:space:]]\{1,\}\([0-9]\{1,\}\)[[:space:]].*$/\1/') ; do
		echo >&3 "Killing PID '$pid'"
		kill "$pid"
	done

	count=$(echo $(ps -fA | grep $MAGIC_NUMBER | grep -v grep | wc -l))
	[ "$count" = 0 ] || {
		echo >&2 '*** Could not kill all processes'
		echo >&2 "count='$count'"
		echo >&2 'Still running:'
		ps -fA | grep -F -e "$MAGIC_NUMBER" | grep -v grep
		exit 1
	}
}

kill_sleeps

# Make sure no process is running
if [ "$(echo $(ps -fA | grep -F -e "$MAGIC_NUMBER" | grep -v grep | wc -l))" != 0 ]; then
	echo >&2 "$0:  *** There is already a process running:"
	ps -fA | grep $MAGIC_NUMBER | grep -v grep >&2
	exit 1
fi

# Start Stu
echo >&3 "../../bin/stu.test -k -j99"
../../bin/stu.test -k -j99 >list.out 2>list.err & pid=$!
echo >&3 pid="$pid"

# Sleep so that there is time for Stu to start all processes
echo >&3 sleep 1
sleep 1

# Make sure all files are created but still empty
for file in B C D E F G H I J K L M N O P Q R S T U V W X Y Z ; do
	[ -r "$file" ]
	[ \! -s $file ]
done

# Terminate Stu
echo >&3 "kill -TERM $pid"
kill -TERM "$pid"

# Give Stu time to kill all processes
echo >&3 sleep 1
sleep 1

# Make sure no process is still running
if [ "$(echo $(ps -fA | grep -F -e "$MAGIC_NUMBER" | grep -v grep | wc -l))" != 0 ]; then
	echo >&2 "$0:  *** There is still a process running:"
	ps -fA | grep -F -e "$MAGIC_NUMBER" | grep -v grep >&2
	exit 1
fi

# Make sure all files were deleted
for file in A B C D E F G H I J K L M N O P Q R S T U V W X Y Z ; do
	[ \! -r $file ]
done

kill_sleeps
