#! /bin/sh

rm -f ? list.* || exit 2

../../bin/stu.test >list.out
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo >&2 '*** error (A)'
	exit 1
}

[ ! -e A -o -s A ] && {
	echo >&2 '*** error:  file not empty'
	exit 1
}

diff list.out stdout-correct || {
	echo >&2 '*** error:  stdout'
	echo >&2 actual stdout:
	echo >&2 ____________
	cat  >&2 list.out
	echo >&2 ____________
	echo >&2 expected stdout:
	echo >&2 ____________
	cat  >&2 stdout-correct
	echo >&2 ____________
	exit 1
}

rm -f ? list.* || exit 2

exit 0
