#! /bin/sh

rm -f ? || exit 2
touch A || exit 2

../../bin/stu.test -s >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 0 ] || {
	echo >&2 "*** Exit code"
	exit 1
}

grep -qF 'Nothing to be done' list.out && {
	echo >&2 "*** Stdout"
	echo list.out:
	echo _______
	cat list.out
	echo _______
	exit 1
}

[ -r list.err ] && [ ! -s list.err ] || {
	echo >&2 "*** Stderr"
	exit 1
}

exit 0
