#! /bin/sh

export STU_STATUS=1
export STU_OPTIONS=y

../../bin/stu.test 2>list.err >list.out
exitstatus=$?

[ "$exitstatus" = 4 ] || {
	echo >&2 '*** Exit status'
	exit 1
}

grep -qF '../../bin/stu.test: *** Refusing to run recursive Stu; unset $STU_STATUS to circumvent' list.err || {
	echo >&2 '*** Error message'
	exit 1
}

exit 0
