#! /bin/sh

rm -Rf data || exit 2

echo >&2 ../../bin/stu.test 
../../bin/stu.test 
if [ "$?" != 0 ]; then
	echo "$0:  *** first stu failed"
	exit 1
fi

echo >&2 touch data/X
touch data/X || {
	exit 1
}

echo >&2 ../../bin/stu.test
../../bin/stu.test >list.output
if [ "$?" != 0 ]; then
	exit 1
fi

grep -qFx 'Targets are up to date' list.output || {
	echo >&2 "$0:  *** stu did not output 'Targets are up to date'"
	exit 1
}

rm -Rf data || exit 2

exit 0
