#! /bin/sh

export STU_STATUS=1

../../stu 2>list.err >list.out
exitcode="$?"

[ "$exitcode" = 2 ] || {
	echo >&2 '*** Wrong exit code'
	exit 1
}

grep -qF '../../stu: *** Refusing to run recursive Stu; unset $STU_STATUS to circumvent' list.err || {
	echo >&2 '*** Missing error message'
	exit 1
}

exit 0
