#! /bin/sh

logfile=${TMP:-/tmp}/stu-$(basename $(pwd)).$$.log

exec 6>"$logfile"

echo >&6 Started
date >&6

rm -f ? list.* || exit 2

# Use the silent option (-s) to avoid false positives, i.e., that the
# greps find the string '@x' erroneously.
../../bin/stu.test -s -j6 >list.out 2>list.err &
pid=$!
echo >&6 pid="$pid"

echo sleep 1
echo >&6 sleep 1
sleep 1 || exit 2

echo >&6 kill -s USR1 "$pid"
kill -s USR1 "$pid" || {
	echo >&2 '*** Kill'
	exit 1
}

>&6 ps -fe | grep -F -e "$pid"

if uname | grep -q -i -F -e 'Linux' ; then
	>&6 ps -e -o command,pid,ppid,pgid,blocked,caught,cls,f,ignored,wchan:30,pending,stat,sched | grep stu
fi

echo >&6 sleep 1
sleep 1
echo kill -s TERM "$pid"
kill -s TERM "$pid"

echo >&6 wait "$pid"
wait "$pid" 2>/dev/null
exitstatus=$?

grep -qE '^STATISTICS  ' list.out || {
	echo >&2 '*** Output A'
	exit 1
}

grep -qF '(2 succeeded, 0 failed, 6 running)' list.out || {
	echo >&2 '*** Output B'
	echo >&2 stdout:
	echo >&2 ________________
	cat  >&2 list.out
	echo >&2 ________________
	exit 1
}

grep -qF " list.M" list.out || {
	echo >&2 '*** Output list.M (1)'
	echo >&2 stdout:
	echo >&2 ________________
	cat  >&2 list.out
	echo >&2 ________________
	exit 1
}

grep -qF " \"list.File 123\"" list.out || {
	echo >&2 '*** Output list.File 123 (1)'
	echo >&2 stdout:
	echo >&2 ________________
	cat  >&2 list.out
	echo >&2 ________________
	exit 1
}

grep -qF " @x" list.out || {
	echo >&2 '*** Output @x (2)'
	echo >&2 stdout:
	echo >&2 ____
	cat >&2 list.out
	echo >&2 ____
	exit 1
}

rm -f ? list.* || exit 2

rm -- "$logfile" || exit 2

exit 0
