#!/bin/sh
. ../../sh/test.sh

LINES=200000
PART=01234567890
LINE=$PART$PART$PART$PART$PART$PART$PART$PART$PART$PART

{
	../../sh/seq "$LINES" | while read -r line ; do
		echo "# $LINE"
	done
	echo "A={CORRECT}"
} |
../../bin/stu.test -f-

grep -q -F -e 'CORRECT' A
