#!/bin/sh
. ../../sh/test.sh

mkdir list.dir

{
	printf '%%cd list.dir\n'
	printf 'B = C;\n'
	printf 'C { echo bcde >C ; }\n'
} >list.stu

../../bin/stu.test -f list.stu

grep -q -F -x -e bcde list.dir/B
