#! /bin/sh

rm -f ? || exit 1

touch A || exit 1

../../stu.test -s >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** Exit code"
	exit 1
}

grep -qFx 'Nothing to be done' list.out || {
	echo >&2 "*** stdout"
	echo list.out:
	echo _______
	cat list.out
	echo _______
	exit 1
}

[ -r list.err -a \! -s list.err ] || {
	echo >&2 "*** stderr"
	exit 1
}

exit 0
