#!/bin/sh
. ../../sh/test.sh

../../bin/stu.test >list.out 2>list.err & pid=$!

sleep 1
kill -s INT "$pid"

set +e
wait $pid
exitstatus=$?
set -e

[ "$exitstatus" = 130 ]
[ \! -h A ]
grep -q -F -e 'removing partially built files' list.err
