#! /bin/sh

rm -f ? list.* || exit 2

../../bin/stu.test -k >list.out 2>list.err
statuscode=$?

[ "$statuscode" = 2 ] || {
	echo >&2 '*** Status code'
	exit 2
}

cmp -s list.out stdout-correct || {
	echo >&2 '*** stdout wrong'
	diff >&2 list.out stdout-correct
	exit 2
}

cmp -s list.err stderr-correct || {
	echo >&2 '*** stderr wrong'
	diff >&2 list.err stderr-correct
	exit 2
}

[ -r Y ] || {
	echo >&2 "*** File 'Y' must exist after execution of Stu"
	exit 2
}

rm -f ? list.* || exit 2

exit 0
