#!/bin/sh
. ../../sh/test.sh

rm -f -- -a -b -c

../../bin/stu.test -J -a -- -a -b -c >list.out 2>list.err

[ -r list.err ] && [ ! -s list.err ] || Error 'stderr'

for name in a b c ; do
	[ -r "-$name" ] || Error "file '-$name'"
done

rm -f -- -a -b -c
