#!/bin/sh
. ../../sh/test.sh

rm -f ?
ln -s W B

echo >&3 ../../bin/stu.test

set +e
../../bin/stu.test >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 0 ] || Error 'exit status'
grep -q -F -e 'Executing B' list.out || Error 'stdout'

rm -f ?

exit 0
