#!/bin/sh
. ../../sh/test.sh

set +e
../../bin/stu.test -f - <<EOF >list.out 2>list.err
:::: # Syntax error
EOF
exitstatus="$?"
set -e

[ "$exitstatus" = 2 ] || Error 'exit status'
grep -q -F -e '<stdin>' list.err || Error 'stderr'
