#! /bin/sh
#
# The -s option (silent) does not suppress the 'Nothing to be done'
# message. 
#

rm -f ?

touch A

../../stu.test -s A >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** Exit code"
	exit 1
}

[ -s list.out ] || {
	echo >&2 "*** stdout"
	echo list.out:
	echo _______
	cat list.out
	echo _______
	exit 1
}

grep -qF 'Nothing to be done' list.out || {
	echo >&2 "*** Expected 'Nothing to be done'"
	exit 1
}

[ -r list.err ] &&  [ \! -s list.err ] || {
 	echo >&2 "*** stderr"
	exit 1
}

exit 0
