#! /bin/sh
#
# The -s option (silent) does suppress the 'File ... exists but has
# no rule' message. 
#

rm -f ?

touch A

../../stu.test -s A >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** Exit code"
	exit 1
}

[ -r list.out ] && [ ! -s list.out ] || {
	echo >&2 "*** stdout must be empty"
	echo list.out:
	echo _______
	cat list.out
	echo _______
	exit 1
}

grep -qFx "No rule for building 'A', but the file exists" list.out && {
	echo >&2 "*** Unexpected 'No rule for ... but the file exists'"
	exit 1
}

[ -r list.err ] &&  [ \! -s list.err ] || {
 	echo >&2 "*** stderr"
	exit 1
}

exit 0
