#!/bin/sh
. ../../sh/test.sh

rm -f A B

now=$(LC_ALL=C date)
year=$(echo $now | sed -e 's,^.* \([0-9][0-9]*\)$,\1,')
year_future=$(expr 2 + $year)
date="$year_future"01010700

touch -t "$date" B

set +e
../../bin/stu.test 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 0 ] || Error 'exit status'
grep -q -F -e "warning: file \"B\" has modification time in the future" list.err ||
	Error 'warning'

# Check that the warning is given just once
[ "$(grep -c -F -e "warning: file \"B\" has modification time in the future" list.err)" = 1 ] ||
	Error 'warning must not be output multiple times'

rm -f A B
