#! /bin/sh
#
# Trivial dependencies.
#
# * stu -a
#	* B, C and A are built
# * touch B C
# * stu -a
#	* A is built

set -e

doo() { echo "$@" ; "$@" ; }

doo rm -f ?

echo ../../stu -a
../../stu -a >list.out 2>list.err
if ! cmp list.out stdout.1 ; then echo >&2 '*** (1out)' ; exit 1 ; fi
[ -r list.err -a \! -s list.err ] || { 
	echo >&2 '*** (1err) stderr must be empty' 
	exit 1 
}

doo sleep 2
doo touch B C
echo ../../stu -a
../../stu -a >list.out 2>list.err
if ! cmp list.out stdout.2 ; then echo >&2 '*** (2out)' ; exit 1 ; fi
[ -s list.err ] && { echo >&2 '*** (2err)' ; exit 1 ; }

exit 0
