#!/bin/sh
. ../../sh/test.sh

rm -f ?

set +e
../../bin/stu.test >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 0 ] || Error 'exit status (1)'
[ -r list.err ] && [ ! -s list.err ] || Error 'stderr (1)'
[ -r A ] || Error 'A'
grep -q -x -F -e 'correct' A || Error 'content'

../../sh/touch_old A 1
../../sh/touch_old C 2
touch B

set +e
../../bin/stu.test >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 0 ] || Error 'exit status (2)'
[ -r list.err ] && [ ! -s list.err ] || Error 'stderr (2)'
grep -q -x -F -e 'Targets are up to date' list.out || Error 'stdout'
