#! /bin/sh

../../bin/stu.test '@" do"' >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 1 ] || {
	echo >&2 '*** Exit status incorrect'
	exit 1
}

grep -qF "no rule to build @\"\\\" do\\\"\"" list.err || {
	echo >&2 '*** stderr'
	echo >&2 ___________________
	cat >&2 list.err
	echo >&2 ___________________
	exit 1
}

exit 0
