#! /bin/sh

unset TERM

../../bin/stu.test -Y >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 2 ] || {
	echo >&2 "*** Expected exit status 2"
	echo >&2 "exitstatus='$exitstatus'"
	exit 1
}

cmp -s list.err stderr-correct || {
	echo >&2 "*** Standard error output"
	diff list.err stderr-correct
	exit 1
}

exit 0
