#! /bin/sh
#
# Trivial dependencies.
#
# * (1) stu
#	* B, D, C and A are built
# * (2) touch D
# * stu
#	* nothing is done
# * (3) rm D
# * stu
#	* nothing is done
# * (4) touch B
# * stu
#	* D, C and A are rebuilt
# * (5) touch B
# * stu
#	* A is rebuilt
# 

rm -f ? || exit 1

#
# (1) 
#

../../stu.test >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** Exitcode (1)"
	exit 1
}

[ -r A ] && [ -r B ] && [ -r C ] && [ -r D ] || {
	echo >&2 '*** (1)'
	exit 1
}

#
# (2)
#

../../sh/touch_old A 2
../../sh/touch_old B 2
../../sh/touch_old C 2
touch D

../../stu.test >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** Exitcode (2)"
	exit 1
}

diff list.out stdout-2 || {
	echo >&2 '*** (2out)' 
	exit 1 
}

[ -r list.err ] && [ ! -s list.err ] || { 
	echo >&2 '*** (2err)' 
	exit 1 
}

#
# (3)
#

rm D

../../stu.test >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** Exitcode (3)"
	exit 1
}

diff list.out stdout-3 || {
	echo >&2 '*** (3out)' 
	exit 1 
}

[ -r list.err ] && [ ! -s list.err ] || { 
	echo >&2 '*** (3err)' 
	exit 1 
}

#
# (4)
#

../../sh/touch_old A 2
../../sh/touch_old C 2
touch B

../../stu.test >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** Exitcode (4)"
	exit 1
}

diff list.out stdout-4 || {
	echo >&2 '*** (4out)' 
	exit 1 
}

[ -r list.err ] && [ ! -s list.err ] || { 
	echo >&2 '*** (4err)' 
	exit 1 
}

#
# (5)
#

../../sh/touch_old A 2
../../sh/touch_old C 2
../../sh/touch_old D 2
touch B

../../stu.test >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 0 ] || {
	echo >&2 "*** Exitcode (5)"
	exit 1
}

diff list.out stdout-5 || {
	echo >&2 '*** (5out)' 
	exit 1 
}

[ -r list.err ] && [ ! -s list.err ] || { 
	echo >&2 '*** (5err)' 
	exit 1 
}

exit 0
