/* Automatically generated by sh/mkversion on 2023-04-08T18:32:02 */

#ifndef VERSION_HH
#define VERSION_HH

#define STU_VERSION "2.7.28"

#define STU_VERSION_MAJOR 2
#define STU_VERSION_MINOR 7
#define STU_VERSION_PATCH 28

#endif /* ! VERSION_HH */
