/* Automatically generated by sh/mkversion on 2023-04-02T11:12:51 */

#ifndef VERSION_HH
#define VERSION_HH

#define STU_VERSION "2.7.18"

#define STU_VERSION_MAJOR 2
#define STU_VERSION_MINOR 7
#define STU_VERSION_PATCH 18

#endif /* ! VERSION_HH */
