/* Automatically generated by sh/mkversion on 2023-04-10T13:19:17 */

#ifndef VERSION_HH
#define VERSION_HH

#define STU_VERSION "2.7.52"

#define STU_VERSION_MAJOR 2
#define STU_VERSION_MINOR 7
#define STU_VERSION_PATCH 52

#endif /* ! VERSION_HH */
