#! /bin/sh

#
# (1) No options
#

echo RUN '(1)'

rm -f ? || exit 2

../../bin/stu.test >list.out 2>list.err
exitstatus=$?

[ "$exitstatus" = 1 ] || {
	echo >&2 "*** Variant without options failed (1)"
	exit 1
}

#
# (2) With -k 
#

echo RUN '(2)'

rm -f ? || exit 2
 
if [ "$(echo $(ps -fA | grep 74634275 | grep -v grep | wc -l))" != 0 ]; then
	echo >&2 "*** There are still processes running from previously (2b)"
	exit 1
fi

../../bin/stu.test -k >list.out 2>list.err &
pid=$!

sleep 2 || exit 2

if [ "$(echo $(ps -fA | grep 74634275 | grep -v grep | wc -l))" = 0 ]; then
	echo >&2 "*** Stu is not running (2a)"
	exit 1
fi

ps -fA | grep "$pid"
kill -TERM "$pid"  || {
	echo >&2 "*** Kill (2)"
	exit 1
}

sleep 1 || exit 2
ps -fA | grep  74634275
ps -fA | grep  stu

if [ "$(echo $(ps -fA | grep 74634275 | grep -v grep | wc -l))" != 0 ]; then
	echo >&2 "*** Stu is still running (2b)"
	ps -fA | grep 74634275 | grep -v grep >&2
	echo >&2 _______________
	exit 1
fi

wait "$pid"
exitstatus=$?

#
# (3) With -j2
#

echo RUN '(3)'
rm -f ? || exit 2

../../bin/stu.test -j2 >list.out 2>list.err
exitstatus=$?

if [ "$exitstatus" != 1 ]; then
	echo >&2 "*** Variant without options failed (3)"
	exit 1
fi

#
# (4) With -j2 -k 
#

echo RUN '(4)'

rm -f ? || exit 2
 
../../bin/stu.test -j2 -k >list.out 2>list.err &
pid=$!

sleep 2 || exit 2

if [ "$(echo $(ps -fA | grep 74634275 | grep -v grep | wc -l))" = 0 ]; then
	echo >&2 "*** Stu is not running (4a)"
	exit 1
fi

kill -TERM "$pid" || {
	echo >&2 '*** Kill (4)'
	exit 1
}

sleep 1 || exit 2

if [ "$(echo $(ps -fA | grep 74634275 | grep -v grep | wc -l))" != 0 ]; then
	echo >&2 "*** Stu is still running (4b)"
	exit 1
fi

#
# End
#

exit 0
