#! /bin/sh
#
# Test that when a single job is executed, that job stays in the
# foreground.  
#

set -e

rm -f ?

echo correct | ../../stu.test -F '>A{cat}'

grep -qF correct A || {
	echo >&2 "*** Expected 'correct' in file 'A'"
	exit 1
}

exit 0
