#! /bin/sh

rm -f A || exit 1

../../stu.test '?A' B >list.out 2>list.err
exitcode="$?"

[ "$exitcode" = 2 ] || {
	echo >&2 "*** Exitcode"
	exit 1
}

[ ! -e A ] || {
	echo >&2 "*** A must not be built"
	exit 1
}

[ ! -e B ] || {
	echo >&2 "*** B must not be built"
	exit 1
}

exit 0
