#! /bin/sh

../../stu.test '@" do"' >list.out 2>list.err 
exitcode="$?"

[ "$exitcode" = 1 ] || {
	echo >&2 '*** exit code'
	exit 1
}

grep -qF "no rule to build @'\" do\"'" list.err || {
	echo >&2 '*** stderr'
	echo >&2 ___________________
	cat >&2 list.err
	echo >&2 ___________________
	exit 1
}

exit 0
