#!/bin/sh
. ../../sh/test.sh

Clean()
{
	[ -e B ] && chmod -R u+rwx B
	../../sh/rm_tmps
}

Clean
trap Clean EXIT

set +e
../../bin/stu.test >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 1 ]
grep -q -F -e 'cannot determine whether file "B/C/D" was built by command' list.err
