#!/bin/sh
. ../../sh/test.sh

export STU_OPTIONS=-Ey

set +e
../../bin/stu.test >list.out 2>list.err
exitstatus=$?
set -e

[ "$exitstatus" = 2 ] || Error 'exit status'
grep -q -F -e 'Explanation: Each Stu script can declare a version to which it is' list.err ||
	Error 'stderr'
