#!/bin/sh
. ../../sh/test.sh

dir=$(pwd)
( cd ../.. ; sh/ccpreload "$dir"/PRELOAD.cc bin/preload.so )

LD_PRELOAD=../../bin/preload.so ../../bin/stu.test >list.out 2>list.err & pid=$!

sleep 1
kill -s QUIT "$pid"

set +e
wait "$pid" 2>/dev/null
exitstatus=$?
set -e

[ "$exitstatus" = 4 ]
grep -q -F -e 'raise' list.err
