#!/bin/sh
. ../../sh/test.sh

rm -f ?

../../bin/stu.test A || Error 'building A'

rm -f C

../../bin/stu.test A || Error 're-building A'

rm -f C

if ../../bin/stu.test A | grep 'Hello >B' ; then
	Error 'unnecessarily re-building B'
fi

exit 0
