#! /bin/sh

doo() { echo "$@" ; "$@" ; }

doo rm -f A

# By calling stu

echo ../../stu
../../stu || exit 1

[ -r A ] || exit 1

echo ../../stu 
../../stu >list.output || exit 1

if fgrep -v 'Nothing to be done' list.output ; then
    exit 1
fi

echo ../../stu @clean
../../stu @clean || exit 1

[ \! -r A ] || exit 1

# By calling stu A

echo ../../stu A
../../stu A || exit 1

[ -r A ] || exit 1

echo ../../stu A
../../stu A >list.output || exit 1

if fgrep -v 'Nothing to be done' list.output ; then
    exit 1
fi

echo ../../stu @clean
../../stu @clean || exit 1

[ \! -r A ] || exit 1

rm list.output

