#! /bin/sh

rm -Rf data-X-dir || exit 2

echo ../../bin/stu.test 
../../bin/stu.test 
if [ "$?" != 0 ]; then
	echo >&2 "*** (1)"
	exit 1
fi

touch data-X-dir/unrelatedfile || exit 2

echo ../../bin/stu.test
../../bin/stu.test >list.output
if [ "$?" != 0 ]; then
	echo >&2 "*** (2)"
	exit 1
fi

grep -qFx 'Targets are up to date' list.output || {
	echo >&2 "*** Stu did not output 'Targets are up to date'"
	exit 1
}

rm -Rf data-X-dir list.output A list.* || exit 2

exit 0
