#! /bin/sh

doo() { echo "$@" ; $@ ; }

rm -f ?

doo touch A 
doo sleep 2

echo ../../stu.test &
../../stu.test &
pid="$!"

kill "$pid"

[ -e A ] || {
	echo >&2 "*** error (a) 'A' must be present"
	exit 1
}

exit 0
